var _require = require("./../promotion/index.js"), SUPERMONKEY_CARD_MENU_ROW = _require.SUPERMONKEY_CARD_MENU_ROW, FACE_BTN_MY = "faceBtnMy", CHARGE_BOTTOM_BTN = "chargeBottomBtn", SEE_VIP_RIGHTS = "seeVipRights", SUPER_RANK_ROW = "superRankRow", BADGE_ROW = "badgeRow", TICKET_ROW = "ticketRow", INVITE_ROW = "inviteRow", MY_GIVEN_ROW = "myGivenRow", NOTICE_MANAGE_ROW = "noticeManageRow", COMPANY_SERVICE_ROW = "companyServiceRow", My = {
    FACE_BTN_MY: FACE_BTN_MY,
    SUPERMONKEY_CARD_MENU_ROW: SUPERMONKEY_CARD_MENU_ROW,
    CHARGE_BOTTOM_BTN: CHARGE_BOTTOM_BTN,
    SEE_VIP_RIGHTS: SEE_VIP_RIGHTS,
    SUPER_RANK_ROW: SUPER_RANK_ROW,
    BADGE_ROW: BADGE_ROW,
    TICKET_ROW: TICKET_ROW,
    INVITE_ROW: INVITE_ROW,
    MY_GIVEN_ROW: MY_GIVEN_ROW,
    NOTICE_MANAGE_ROW: NOTICE_MANAGE_ROW,
    COMPANY_SERVICE_ROW: COMPANY_SERVICE_ROW
};

module.exports = {
    My: My
};