Object.defineProperty(exports, "__esModule", {
    value: !0
}), exports.FETCH_PERSONAL_INVOCE_LIST = exports.FETCH_CLASS_INVOCE_LIST = exports.FETCH_RECHARGE_INVOCE_LIST = exports.FETCH_SHARE_PIC_URL = exports.FETCH_SUPER_CHANGE_RECORDS = exports.FETCH_BOOKING_RECORDS = exports.FETCH_TRAINER_INDEX = exports.FETCH_MY_GIVEN_LIST = exports.FETCH_CLASS_BOOKING_DETAIL = exports.FETCH_CLASS_DETAIL = exports.FETCH_BOX_CLASS_SCHEDULE_LIST = exports.FETCH_CLASS_SCHEDULE_LIST = void 0;

var FETCH_CLASS_SCHEDULE_LIST = "FETCH_CLASS_SCHEDULE_LIST";

exports.FETCH_CLASS_SCHEDULE_LIST = FETCH_CLASS_SCHEDULE_LIST;

var FETCH_BOX_CLASS_SCHEDULE_LIST = "FETCH_BOX_CLASS_SCHEDULE_LIST";

exports.FETCH_BOX_CLASS_SCHEDULE_LIST = FETCH_BOX_CLASS_SCHEDULE_LIST;

var FETCH_CLASS_DETAIL = "FETCH_CLASS_DETAIL";

exports.FETCH_CLASS_DETAIL = FETCH_CLASS_DETAIL;

var FETCH_CLASS_BOOKING_DETAIL = "FETCH_CLASS_BOOKING_DETAIL";

exports.FETCH_CLASS_BOOKING_DETAIL = FETCH_CLASS_BOOKING_DETAIL;

var FETCH_MY_GIVEN_LIST = "FETCH_MY_GIVEN_LIST";

exports.FETCH_MY_GIVEN_LIST = FETCH_MY_GIVEN_LIST;

var FETCH_TRAINER_INDEX = "FETCH_TRAINER_INDEX";

exports.FETCH_TRAINER_INDEX = FETCH_TRAINER_INDEX;

var FETCH_BOOKING_RECORDS = "FETCH_BOOKING_RECORDS";

exports.FETCH_BOOKING_RECORDS = FETCH_BOOKING_RECORDS;

var FETCH_SUPER_CHANGE_RECORDS = "FETCH_SUPER_CHANGE_RECORDS";

exports.FETCH_SUPER_CHANGE_RECORDS = FETCH_SUPER_CHANGE_RECORDS;

var FETCH_SHARE_PIC_URL = "FETCH_SHARE_PIC_URL";

exports.FETCH_SHARE_PIC_URL = FETCH_SHARE_PIC_URL;

var FETCH_RECHARGE_INVOCE_LIST = "FETCH_RECHARGE_INVOCE_LIST";

exports.FETCH_RECHARGE_INVOCE_LIST = FETCH_RECHARGE_INVOCE_LIST;

var FETCH_CLASS_INVOCE_LIST = "FETCH_CLASS_INVOCE_LIST";

exports.FETCH_CLASS_INVOCE_LIST = FETCH_CLASS_INVOCE_LIST;

var FETCH_PERSONAL_INVOCE_LIST = "FETCH_PERSONAL_INVOCE_LIST";

exports.FETCH_PERSONAL_INVOCE_LIST = FETCH_PERSONAL_INVOCE_LIST;