Object.defineProperty(exports, "__esModule", {
    value: !0
}), Object.defineProperty(exports, "FETCH_LOADING", {
    enumerable: !0,
    get: function() {
        return _types.FETCH_LOADING;
    }
}), Object.defineProperty(exports, "FETCH_SUCCESS", {
    enumerable: !0,
    get: function() {
        return _types.FETCH_SUCCESS;
    }
}), Object.defineProperty(exports, "FETCH_FAILURE", {
    enumerable: !0,
    get: function() {
        return _types.FETCH_FAILURE;
    }
}), Object.defineProperty(exports, "FETCH_CANCEL", {
    enumerable: !0,
    get: function() {
        return _types.FETCH_CANCEL;
    }
}), exports.PERSONAL_BOOKING_DETAIL_GET_LOADING = exports.PERSONAL_BOOKING_DETAIL_GET = exports.PERSONAL_BOOKING_SUCCESS_INFO_GET_FAILURE = exports.PERSONAL_BOOKING_SUCCESS_INFO_GET_SUCCESS = exports.PERSONAL_BOOKING_SUCCESS_INFO_GET_LOADING = exports.PERSONAL_BOOKING_SUCCESS_INFO_GET = exports.PERSONAL_PAY_SUBMIT_FAILURE = exports.PERSONAL_PAY_SUBMIT_SUCCESS = exports.PERSONAL_PAY_SUBMIT_LOADING = exports.PERSONAL_PAY_SUBMIT = exports.PERSONAL_BOOKING_INFO_GET_FAILURE = exports.PERSONAL_BOOKING_INFO_GET_SUCCESS = exports.PERSONAL_BOOKING_INFO_GET_LOADING = exports.PERSONAL_BOOKING_INFO_GET = exports.PERSONAL_CLASS_DETAIL_GET_FAILURE = exports.PERSONAL_CLASS_DETAIL_GET_SUCCESS = exports.PERSONAL_CLASS_DETAIL_GET_LOADING = exports.PERSONAL_CLASS_DETAIL_GET = exports.FETCH_PERSONAL_CLASS_DETAIL = exports.PERSONAL_BOX_LIST_GET_FAILURE = exports.PERSONAL_BOX_LIST_GET_SUCCESS = exports.PERSONAL_BOX_LIST_GET_LOADING = exports.PERSONAL_BOX_LIST_GET = exports.FETCH_PERSONAL_BOX_LIST = exports.PERSONAL_LIST_GET_FAILURE = exports.PERSONAL_LIST_GET_SUCCESS = exports.PERSONAL_LIST_GET_LOADING = exports.PERSONAL_LIST_GET = exports.CLASS_EVALUATION_POST = exports.CLASS_EVALUATION_GET = exports.CLASS_BOOKING_REFUND_POST = exports.CLASS_BOOKING_REFUND_GET = exports.CLASS_BOOKING_DETAIL_GET_SUCCESS = exports.CLASS_BOOKING_DETAIL_GET = exports.CLASS_BOOKING_SUCCESS_GET_SUCCESS = exports.CLASS_BOOKING_SUCCESS_GET = exports.CLASS_BOOKING_CONFIRM_BALANCE_PAY_POST_SUCCESS = exports.CLASS_BOOKING_CONFIRM_BALANCE_PAY_POST = exports.CLASS_BOOKING_CONFIRM_WX_PAY_POST_SUCCESS = exports.CLASS_BOOKING_CONFIRM_WX_PAY_POST = exports.CLASS_BOOKING_CONFIRM_GET_SUCCESS = exports.CLASS_BOOKING_CONFIRM_GET = exports.CLASS_DETAIL_GET_SUCCESS = exports.CLASS_DETAIL_GET = exports.BOX_CLASS_SCHEDULE_LIST_GET_SUCCESS = exports.BOX_CLASS_SCHEDULE_LIST_GET = exports.CLASS_SCHEDULE_LIST_GET_FAILURE = exports.CLASS_SCHEDULE_LIST_GET_SUCCESS = exports.CLASS_SCHEDULE_LIST_GET = exports.BOX_PAY_INFO_POST_FAILURE = exports.BOX_PAY_INFO_POST_SUCCESS = exports.BOX_PAY_INFO_POST_LOADING = exports.BOX_PAY_INFO_POST = exports.APPLY_BOX_REFUND = exports.BOX_REFUND_INFO_GET = exports.BOOKING_DETAIL_BOX_GET_FAILURE = exports.BOOKING_DETAIL_BOX_GET_SUCCESS = exports.BOOKING_DETAIL_BOX_GET_LOADING = exports.BOOKING_DETAIL_BOX_GET = exports.BOX_BOOKING_SUCCESS_INFO_GET = exports.BOX_BOOKING_TIME_CHECK = exports.BOX_BOOKING_CONFIRM_INFO_GET_FAILURE = exports.BOX_BOOKING_CONFIRM_INFO_GET_SUCCESS = exports.BOX_BOOKING_CONFIRM_INFO_GET_LOADING = exports.BOX_BOOKING_CONFIRM_INFO_GET = exports.BOX_DETAIL_GET_FAILURE = exports.BOX_DETAIL_GET_SUCCESS = exports.BOX_DETAIL_GET_LOADING = exports.BOX_DETAIL_GET = exports.BOX_DELFAV_POST_FAILURE = exports.BOX_DELFAV_POST_SUCCESS = exports.BOX_DELFAV_POST_LOADING = exports.BOX_DELFAV_POST = exports.BOX_ADDFAV_POST_FAILURE = exports.BOX_ADDFAV_POST_SUCCESS = exports.BOX_ADDFAV_POST_LOADING = exports.BOX_ADDFAV_POST = exports.BOX_LIST_GET_FAILURE = exports.BOX_LIST_GET_SUCCESS = exports.BOX_LIST_GET_LOADING = exports.BOX_LIST_GET = exports.CITY_LOCATION_GET_FAILURE = exports.CITY_LOCATION_GET_SUCCESS = exports.CITY_LOCATION_GET = exports.PROMOTION_INIT_SUCCESS = exports.PROMOTION_INIT = exports.PROMOTION_INIT_JSON = exports.PROMOTION_GET_BY_POSITIONID_SUCCESS = exports.PROMOTION_GET_BY_POSITIONID = exports.MESSAGE_INFO_GET = exports.INIT_INFO_FAILURE = exports.INIT_INFO_SUCCESS = exports.INIT_INFO_LOADING = exports.INIT_INFO = exports.LOGIN_REGISTER_SUCCESS = exports.LOGIN_REGISTER = exports.LOGIN_FAILURE = exports.LOGIN_SUCCESS = exports.LOGIN_LOADING = exports.LOGIN = void 0, 
exports.VIP_DETAIL_INFO_GET_FAILURE = exports.VIP_DETAIL_INFO_GET_SUCCESS = exports.VIP_DETAIL_INFO_GET_LOADING = exports.VIP_DETAIL_INFO_GET = exports.USER_EXT_POST_FAILURE = exports.USER_EXT_POST_SUCCESS = exports.USER_EXT_POST_LOADING = exports.USER_EXT_POST = exports.USER_EXT_GET_FAILURE = exports.USER_EXT_GET_SUCCESS = exports.USER_EXT_GET_LOADING = exports.USER_EXT_GET = exports.MY_INFO_GET_FAILURE = exports.MY_INFO_GET_LOADING = exports.MY_INFO_GET_SUCCESS = exports.MY_INFO_GET = exports.RECHARGE_ORDER_POST_FAILURE = exports.RECHARGE_ORDER_POST_SUCCESS = exports.RECHARGE_ORDER_POST_LOADING = exports.RECHARGE_ORDER_POST = exports.RECHARGE_CONFIRM_GET_FAILURE = exports.RECHARGE_CONFIRM_GET_SUCCESS = exports.RECHARGE_CONFIRM_GET_LOADING = exports.RECHARGE_CONFIRM_GET = exports.BOOKING_RECORDS_GET_FAILURE = exports.BOOKING_RECORDS_GET_SUCCESS = exports.BOOKING_RECORDS_GET_LOADING = exports.BOOKING_RECORDS_GET = exports.MY_BOOKING_INFO_GET_FAILURE = exports.MY_BOOKING_INFO_GET_SUCCESS = exports.MY_BOOKING_INFO_GET_LOADING = exports.MY_BOOKING_INFO_GET = exports.ONLINE_CAMP_TRAINER_LIST_GET_SUCCESS = exports.ONLINE_CAMP_TRAINER_LIST_GET = exports.TRAINER_INDEX_GET_SUCCESS = exports.TRAINER_INDEX_GET = exports.MY_GIVEN_LIST_GET_SUCCESS = exports.MY_GIVEN_LIST_GET = exports.GIVE_CLASS_REFUND_POST = exports.GIVE_CLASS_BOOKING_DETAIL_GET_SUCCESS = exports.GIVE_CLASS_BOOKING_DETAIL_GET = exports.GIVE_CLASS_DETAIL_GET_SUCCESS = exports.GIVE_CLASS_DETAIL_GET = exports.GIVE_CLASS_CONFIRM_INFO_GET_SUCCESS = exports.GIVE_CLASS_CONFIRM_INFO_GET = exports.GIVE_CLASS_RECEIVE_INFO_GET_SUCCESS = exports.GIVE_CLASS_RECEIVE_INFO_GET = exports.BOX_CAMP_LIST_GET_SUCCESS = exports.BOX_CAMP_LIST_GET = exports.CAMP_BOOKING_SUCCESS_GET = exports.CAMP_BOOKING_DETAIL_GET_SUCCESS = exports.CAMP_BOOKING_DETAIL_GET = exports.CAMP_APPLY_REFUND_POST = exports.CAMP_REFUND_INFO_GET = exports.CAMP_BOOKING_CONFIRM_WX_PAY_POST_SUCCESS = exports.CAMP_BOOKING_CONFIRM_WX_PAY_POST = exports.CAMP_BOOKING_CONFIRM_BALANCE_PAY_POST_SUCCESS = exports.CAMP_BOOKING_CONFIRM_BALANCE_PAY_POST = exports.CAMP_BOOKING_CONFIRM_INFO_GET_SUCCESS = exports.CAMP_BOOKING_CONFIRM_INFO_GET = exports.CAMP_UNSUBSCRIBE_GET = exports.CAMP_SUBSCRIBE_GET = exports.CAMP_DETAIL_GET_SUCCESS = exports.CAMP_DETAIL_GET = exports.CAMP_LIST_GET_SUCCESS = exports.CAMP_LIST_GET = exports.SUBMIT_TRAIN_BOOKING_DATE_GET_FAILURE = exports.SUBMIT_TRAIN_BOOKING_DATE_GET_LOADING = exports.SUBMIT_TRAIN_BOOKING_DATE_GET_SUCCESS = exports.SUBMIT_TRAIN_BOOKING_DATE_GET = exports.TRAIN_BOOKING_DATE_GET_FAILURE = exports.TRAIN_BOOKING_DATE_GET_LOADING = exports.TRAIN_BOOKING_DATE_GET_SUCCESS = exports.TRAIN_BOOKING_DATE_GET = exports.PERSONAL_CANCELED_TRAIN_LIST_GET_SUCCESS = exports.PERSONAL_CANCELED_TRAIN_LIST_GET = exports.PERSONAL_TRAIN_LIST_GET_SUCCESS = exports.PERSONAL_TRAIN_LIST_GET = exports.PERSONAL_RESERVE_VERIFY_SUCCESS = exports.PERSONAL_RESERVE_VERIFY = exports.PERSONAL_RESERVE_CANCEL_SUCCESS = exports.PERSONAL_RESERVE_CANCEL = exports.PERSONAL_RESERVE_REJECT_SUCCESS = exports.PERSONAL_RESERVE_REJECT = exports.PERSONAL_RESERVE_ACCEPT_SUCCESS = exports.PERSONAL_RESERVE_ACCEPT = exports.PERSONAL_REFUND_APPLY_FAILURE = exports.PERSONAL_REFUND_APPLY_SUCCESS = exports.PERSONAL_REFUND_APPLY_LOADING = exports.PERSONAL_REFUND_APPLY = exports.PERSONAL_REFUND_INFO_GET_FAILURE = exports.PERSONAL_REFUND_INFO_GET_SUCCESS = exports.PERSONAL_REFUND_INFO_GET_LOADING = exports.PERSONAL_REFUND_INFO_GET = exports.OLD_PERSONAL_BOOKING_DETAIL_GET_FAILURE = exports.OLD_PERSONAL_BOOKING_DETAIL_GET_SUCCESS = exports.OLD_PERSONAL_BOOKING_DETAIL_GET_LOADING = exports.OLD_PERSONAL_BOOKING_DETAIL_GET = exports.PERSONAL_BOOKING_DETAIL_GET_FAILURE = exports.PERSONAL_BOOKING_DETAIL_GET_SUCCESS = void 0, 
exports.NOVICE_CLASS_LIST_GET_SUCCESS = exports.NOVICE_CLASS_LIST_GET = exports.CONFIRM_MODAL_POST = exports.OPTION_LIST_GET_FAILURE = exports.OPTION_LIST_GET_SUCCESS = exports.OPTION_LIST_GET_LOADING = exports.OPTION_LIST_GET = exports.CARD_RETURN_CANCEL_FAILURE = exports.CARD_RETURN_CANCEL_SUCCESS = exports.CARD_RETURN_CANCEL_LOADING = exports.CARD_RETURN_CANCEL = exports.CARD_RETURN_SUBMIT_FAILURE = exports.CARD_RETURN_SUBMIT_SUCCESS = exports.CARD_RETURN_SUBMIT_LOADING = exports.CARD_RETURN_SUBMIT = exports.BALANCE_RECORDS_GET_FAILURE = exports.BALANCE_RECORDS_GET_SUCCESS = exports.BALANCE_RECORDS_GET_LOADING = exports.BALANCE_RECORDS_GET = exports.SUPERALLIANCETICKET_IDENTITY_GET_FAILURE = exports.SUPERALLIANCETICKET_IDENTITY_GET_SUCCESS = exports.SUPERALLIANCETICKET_IDENTITY_GET_LOADING = exports.SUPERALLIANCETICKET_CODE_POST = exports.SUPERALLIANCETICKET_IDENTITY_GET = exports.BADGE_USER_LIST_GET_FAILURE = exports.BADGE_USER_LIST_GET_LOADING = exports.BADGE_USER_LIST_GET_SUCCESS = exports.BADGE_USER_LIST_GET = exports.BADGE_DETAIL_GET_FAILURE = exports.BADGE_DETAIL_GET_LOADING = exports.BADGE_DETAIL_GET_SUCCESS = exports.BADGE_DETAIL_GET = exports.BADGE_INFO_GET_FAILURE = exports.BADGE_INFO_GET_LOADING = exports.BADGE_INFO_GET_SUCCESS = exports.BADGE_INFO_GET = exports.PICTURE_SHARE_URL_GET_FAILURE = exports.PICTURE_SHARE_URL_GET_SUCCESS = exports.PICTURE_SHARE_URL_GET_LOADING = exports.PICTURE_SHARE_URL_GET = exports.INVOICE_BLUE_SUBMIT_FAILURE = exports.INVOICE_BLUE_SUBMIT_SUCCESS = exports.INVOICE_BLUE_SUBMIT = exports.WXPAY_INVOICE_HISTORY_GET_SUCCESS = exports.WXPAY_INVOICE_HISTORY_GET = exports.WXPAY_ORDER_LIST_INVOICE_GET_SUCCESS = exports.WXPAY_ORDER_LIST_INVOICE_GET = exports.WXPAY_ORDER_LIST_GET_SUCCESS = exports.WXPAY_ORDER_LIST_GET = exports.GROUP_RANK_GET_SUCCESS = exports.GROUP_RANK_GET = exports.SUPER_RANK_POSTER_GET = exports.SUPER_RANK_GET_SUCCESS = exports.SUPER_RANK_GET = exports.SUBSCRIBE_EVENT_POST_SUCCESS = exports.SUBSCRIBE_EVENT_POST = exports.ORDER_MESSAGE_LIST_GET_SUCCESS = exports.ORDER_MESSAGE_LIST_GET = exports.SUBSCRIBE_MESSAGE_POST_SUCCESS = exports.SUBSCRIBE_MESSAGE_POST = exports.MESSAGE_MANAGE_LIST_GET_SUCCESS = exports.MESSAGE_MANAGE_LIST_GET = exports.NOTICE_LIST_GET = exports.BIND_PHONE_POST = exports.BIND_PHONE_BY_WX_GET = exports.PHONE_CODE_GET = exports.PAY_FAILURE_RECEIPT = exports.PAY_SUCCESS_RECEIPT = exports.EXCHANGE_TICKET_CODE_POST = exports.INVALID_TICKETS_GET_SUCCESS = exports.INVALID_TICKETS_GET = exports.MY_TICKETS_GET_SUCCESS = exports.MY_TICKETS_GET = exports.ONLINE_CAMP_DETAIL_SCHEDULE_GET_SUCCESS = exports.ONLINE_CAMP_DETAIL_SCHEDULE_GET = exports.ONLINE_CAMP_DETAIL_GET_SUCCESS = exports.ONLINE_CAMP_DETAIL_GET = exports.ONLINE_CAMP_LIST_GET_SUCCESS = exports.ONLINE_CAMP_LIST_GET = exports.ONLINE_COURSE_LIST_GET_SUCCESS = exports.ONLINE_COURSE_LIST_GET = exports.ONLINE_CAMP_HOME_DATA_GET_SUCCESS = exports.ONLINE_CAMP_HOME_DATA_GET = exports.SUPER_CHANGE_RECORDS_GET_FAILURE = exports.SUPER_CHANGE_RECORDS_GET_SUCCESS = exports.SUPER_CHANGE_RECORDS_GET_LOADING = exports.SUPER_CHANGE_RECORDS_GET = void 0;

var _types = require("./../../imports/types.js"), LOGIN = "LOGIN";

exports.LOGIN = LOGIN;

var LOGIN_LOADING = "LOGIN_LOADING";

exports.LOGIN_LOADING = LOGIN_LOADING;

var LOGIN_SUCCESS = "LOGIN_SUCCESS";

exports.LOGIN_SUCCESS = LOGIN_SUCCESS;

var LOGIN_FAILURE = "LOGIN_FAILURE";

exports.LOGIN_FAILURE = LOGIN_FAILURE;

var LOGIN_REGISTER = "LOGIN_REGISTER";

exports.LOGIN_REGISTER = LOGIN_REGISTER;

var LOGIN_REGISTER_SUCCESS = "LOGIN_REGISTER_SUCCESS";

exports.LOGIN_REGISTER_SUCCESS = LOGIN_REGISTER_SUCCESS;

var INIT_INFO = "INIT_INFO";

exports.INIT_INFO = INIT_INFO;

var INIT_INFO_LOADING = "INIT_INFO_LOADING";

exports.INIT_INFO_LOADING = INIT_INFO_LOADING;

var INIT_INFO_SUCCESS = "INIT_INFO_SUCCESS";

exports.INIT_INFO_SUCCESS = INIT_INFO_SUCCESS;

var INIT_INFO_FAILURE = "INIT_INFO_FAILURE";

exports.INIT_INFO_FAILURE = INIT_INFO_FAILURE;

var MESSAGE_INFO_GET = "MESSAGE_INFO_GET";

exports.MESSAGE_INFO_GET = MESSAGE_INFO_GET;

var PROMOTION_GET_BY_POSITIONID = "PROMOTION_GET_BY_POSITIONID";

exports.PROMOTION_GET_BY_POSITIONID = PROMOTION_GET_BY_POSITIONID;

var PROMOTION_GET_BY_POSITIONID_SUCCESS = "PROMOTION_GET_BY_POSITIONID_SUCCESS";

exports.PROMOTION_GET_BY_POSITIONID_SUCCESS = PROMOTION_GET_BY_POSITIONID_SUCCESS;

var PROMOTION_INIT_JSON = "PROMOTION_INIT_JSON";

exports.PROMOTION_INIT_JSON = PROMOTION_INIT_JSON;

var PROMOTION_INIT = "PROMOTION_INIT";

exports.PROMOTION_INIT = PROMOTION_INIT;

var PROMOTION_INIT_SUCCESS = "PROMOTION_INIT_SUCCESS";

exports.PROMOTION_INIT_SUCCESS = PROMOTION_INIT_SUCCESS;

var CITY_LOCATION_GET = "CITY_LOCATION_GET";

exports.CITY_LOCATION_GET = CITY_LOCATION_GET;

var CITY_LOCATION_GET_SUCCESS = "CITY_LOCATION_GET_SUCCESS";

exports.CITY_LOCATION_GET_SUCCESS = CITY_LOCATION_GET_SUCCESS;

var CITY_LOCATION_GET_FAILURE = "CITY_LOCATION_GET_FAILURE";

exports.CITY_LOCATION_GET_FAILURE = CITY_LOCATION_GET_FAILURE;

var BOX_LIST_GET = "BOX_LIST_GET";

exports.BOX_LIST_GET = BOX_LIST_GET;

var BOX_LIST_GET_LOADING = "BOX_LIST_GET_LOADING";

exports.BOX_LIST_GET_LOADING = BOX_LIST_GET_LOADING;

var BOX_LIST_GET_SUCCESS = "BOX_LIST_GET_SUCCESS";

exports.BOX_LIST_GET_SUCCESS = BOX_LIST_GET_SUCCESS;

var BOX_LIST_GET_FAILURE = "BOX_LIST_GET_FAILURE";

exports.BOX_LIST_GET_FAILURE = BOX_LIST_GET_FAILURE;

var BOX_ADDFAV_POST = "BOX_ADDFAV_POST";

exports.BOX_ADDFAV_POST = BOX_ADDFAV_POST;

var BOX_ADDFAV_POST_LOADING = "BOX_ADDFAV_POST_LOADING";

exports.BOX_ADDFAV_POST_LOADING = BOX_ADDFAV_POST_LOADING;

var BOX_ADDFAV_POST_SUCCESS = "BOX_ADDFAV_POST_SUCCESS";

exports.BOX_ADDFAV_POST_SUCCESS = BOX_ADDFAV_POST_SUCCESS;

var BOX_ADDFAV_POST_FAILURE = "BOX_ADDFAV_POST_FAILURE";

exports.BOX_ADDFAV_POST_FAILURE = BOX_ADDFAV_POST_FAILURE;

var BOX_DELFAV_POST = "BOX_DELFAV_POST";

exports.BOX_DELFAV_POST = BOX_DELFAV_POST;

var BOX_DELFAV_POST_LOADING = "BOX_DELFAV_POST_LOADING";

exports.BOX_DELFAV_POST_LOADING = BOX_DELFAV_POST_LOADING;

var BOX_DELFAV_POST_SUCCESS = "BOX_DELFAV_POST_SUCCESS";

exports.BOX_DELFAV_POST_SUCCESS = BOX_DELFAV_POST_SUCCESS;

var BOX_DELFAV_POST_FAILURE = "BOX_DELFAV_POST_FAILURE";

exports.BOX_DELFAV_POST_FAILURE = BOX_DELFAV_POST_FAILURE;

var BOX_DETAIL_GET = "BOX_DETAIL_GET";

exports.BOX_DETAIL_GET = BOX_DETAIL_GET;

var BOX_DETAIL_GET_LOADING = "BOX_DETAIL_GET_LOADING";

exports.BOX_DETAIL_GET_LOADING = BOX_DETAIL_GET_LOADING;

var BOX_DETAIL_GET_SUCCESS = "BOX_DETAIL_GET_SUCCESS";

exports.BOX_DETAIL_GET_SUCCESS = BOX_DETAIL_GET_SUCCESS;

var BOX_DETAIL_GET_FAILURE = "BOX_DETAIL_GET_FAILURE";

exports.BOX_DETAIL_GET_FAILURE = BOX_DETAIL_GET_FAILURE;

var BOX_BOOKING_CONFIRM_INFO_GET = "BOX_BOOKING_CONFIRM_INFO_GET";

exports.BOX_BOOKING_CONFIRM_INFO_GET = BOX_BOOKING_CONFIRM_INFO_GET;

var BOX_BOOKING_CONFIRM_INFO_GET_LOADING = "BOX_BOOKING_CONFIRM_INFO_GET_LOADING";

exports.BOX_BOOKING_CONFIRM_INFO_GET_LOADING = BOX_BOOKING_CONFIRM_INFO_GET_LOADING;

var BOX_BOOKING_CONFIRM_INFO_GET_SUCCESS = "BOX_BOOKING_CONFIRM_INFO_GET_SUCCESS";

exports.BOX_BOOKING_CONFIRM_INFO_GET_SUCCESS = BOX_BOOKING_CONFIRM_INFO_GET_SUCCESS;

var BOX_BOOKING_CONFIRM_INFO_GET_FAILURE = "BOX_BOOKING_CONFIRM_INFO_GET_FAILURE";

exports.BOX_BOOKING_CONFIRM_INFO_GET_FAILURE = BOX_BOOKING_CONFIRM_INFO_GET_FAILURE;

var BOX_BOOKING_TIME_CHECK = "BOX_BOOKING_TIME_CHECK";

exports.BOX_BOOKING_TIME_CHECK = BOX_BOOKING_TIME_CHECK;

var BOX_BOOKING_SUCCESS_INFO_GET = "BOX_BOOKING_SUCCESS_INFO_GET";

exports.BOX_BOOKING_SUCCESS_INFO_GET = BOX_BOOKING_SUCCESS_INFO_GET;

var BOOKING_DETAIL_BOX_GET = "BOOKING_DETAIL_BOX_GET";

exports.BOOKING_DETAIL_BOX_GET = BOOKING_DETAIL_BOX_GET;

var BOOKING_DETAIL_BOX_GET_LOADING = "BOOKING_DETAIL_BOX_GET_LOADING";

exports.BOOKING_DETAIL_BOX_GET_LOADING = BOOKING_DETAIL_BOX_GET_LOADING;

var BOOKING_DETAIL_BOX_GET_SUCCESS = "BOOKING_DETAIL_BOX_GET_SUCCESS";

exports.BOOKING_DETAIL_BOX_GET_SUCCESS = BOOKING_DETAIL_BOX_GET_SUCCESS;

var BOOKING_DETAIL_BOX_GET_FAILURE = "BOOKING_DETAIL_BOX_GET_FAILURE";

exports.BOOKING_DETAIL_BOX_GET_FAILURE = BOOKING_DETAIL_BOX_GET_FAILURE;

var BOX_REFUND_INFO_GET = "BOX_REFUND_INFO_GET";

exports.BOX_REFUND_INFO_GET = BOX_REFUND_INFO_GET;

var APPLY_BOX_REFUND = "APPLY_BOX_REFUND";

exports.APPLY_BOX_REFUND = APPLY_BOX_REFUND;

var BOX_PAY_INFO_POST = "BOX_PAY_INFO_POST";

exports.BOX_PAY_INFO_POST = BOX_PAY_INFO_POST;

var BOX_PAY_INFO_POST_LOADING = "BOX_PAY_INFO_POST_LOADING";

exports.BOX_PAY_INFO_POST_LOADING = BOX_PAY_INFO_POST_LOADING;

var BOX_PAY_INFO_POST_SUCCESS = "BOX_PAY_INFO_POST_SUCCESS";

exports.BOX_PAY_INFO_POST_SUCCESS = BOX_PAY_INFO_POST_SUCCESS;

var BOX_PAY_INFO_POST_FAILURE = "BOX_PAY_INFO_POST_FAILURE";

exports.BOX_PAY_INFO_POST_FAILURE = BOX_PAY_INFO_POST_FAILURE;

var CLASS_SCHEDULE_LIST_GET = "CLASS_SCHEDULE_LIST_GET";

exports.CLASS_SCHEDULE_LIST_GET = CLASS_SCHEDULE_LIST_GET;

var CLASS_SCHEDULE_LIST_GET_SUCCESS = "CLASS_SCHEDULE_LIST_GET_SUCCESS";

exports.CLASS_SCHEDULE_LIST_GET_SUCCESS = CLASS_SCHEDULE_LIST_GET_SUCCESS;

var CLASS_SCHEDULE_LIST_GET_FAILURE = "CLASS_SCHEDULE_LIST_GET_FAILURE";

exports.CLASS_SCHEDULE_LIST_GET_FAILURE = CLASS_SCHEDULE_LIST_GET_FAILURE;

var BOX_CLASS_SCHEDULE_LIST_GET = "BOX_CLASS_SCHEDULE_LIST_GET";

exports.BOX_CLASS_SCHEDULE_LIST_GET = BOX_CLASS_SCHEDULE_LIST_GET;

var BOX_CLASS_SCHEDULE_LIST_GET_SUCCESS = "BOX_CLASS_SCHEDULE_LIST_GET_SUCCESS";

exports.BOX_CLASS_SCHEDULE_LIST_GET_SUCCESS = BOX_CLASS_SCHEDULE_LIST_GET_SUCCESS;

var CLASS_DETAIL_GET = "CLASS_DETAIL_GET";

exports.CLASS_DETAIL_GET = CLASS_DETAIL_GET;

var CLASS_DETAIL_GET_SUCCESS = "CLASS_DETAIL_GET_SUCCESS";

exports.CLASS_DETAIL_GET_SUCCESS = CLASS_DETAIL_GET_SUCCESS;

var CLASS_BOOKING_CONFIRM_GET = "CLASS_BOOKING_CONFIRM_GET";

exports.CLASS_BOOKING_CONFIRM_GET = CLASS_BOOKING_CONFIRM_GET;

var CLASS_BOOKING_CONFIRM_GET_SUCCESS = "CLASS_BOOKING_CONFIRM_GET_SUCCESS";

exports.CLASS_BOOKING_CONFIRM_GET_SUCCESS = CLASS_BOOKING_CONFIRM_GET_SUCCESS;

var CLASS_BOOKING_CONFIRM_WX_PAY_POST = "CLASS_BOOKING_CONFIRM_WX_PAY_POST";

exports.CLASS_BOOKING_CONFIRM_WX_PAY_POST = CLASS_BOOKING_CONFIRM_WX_PAY_POST;

var CLASS_BOOKING_CONFIRM_WX_PAY_POST_SUCCESS = "CLASS_BOOKING_CONFIRM_WX_PAY_POST_SUCCESS";

exports.CLASS_BOOKING_CONFIRM_WX_PAY_POST_SUCCESS = CLASS_BOOKING_CONFIRM_WX_PAY_POST_SUCCESS;

var CLASS_BOOKING_CONFIRM_BALANCE_PAY_POST = "CLASS_BOOKING_CONFIRM_BALANCE_PAY_POST";

exports.CLASS_BOOKING_CONFIRM_BALANCE_PAY_POST = CLASS_BOOKING_CONFIRM_BALANCE_PAY_POST;

var CLASS_BOOKING_CONFIRM_BALANCE_PAY_POST_SUCCESS = "CLASS_BOOKING_CONFIRM_BALANCE_PAY_POST_SUCCESS";

exports.CLASS_BOOKING_CONFIRM_BALANCE_PAY_POST_SUCCESS = CLASS_BOOKING_CONFIRM_BALANCE_PAY_POST_SUCCESS;

var CLASS_BOOKING_SUCCESS_GET = "CLASS_BOOKING_SUCCESS_GET";

exports.CLASS_BOOKING_SUCCESS_GET = CLASS_BOOKING_SUCCESS_GET;

var CLASS_BOOKING_SUCCESS_GET_SUCCESS = "CLASS_BOOKING_SUCCESS_GET_SUCCESS";

exports.CLASS_BOOKING_SUCCESS_GET_SUCCESS = CLASS_BOOKING_SUCCESS_GET_SUCCESS;

var CLASS_BOOKING_DETAIL_GET = "CLASS_BOOKING_DETAIL_GET";

exports.CLASS_BOOKING_DETAIL_GET = CLASS_BOOKING_DETAIL_GET;

var CLASS_BOOKING_DETAIL_GET_SUCCESS = "CLASS_BOOKING_DETAIL_GET_SUCCESS";

exports.CLASS_BOOKING_DETAIL_GET_SUCCESS = CLASS_BOOKING_DETAIL_GET_SUCCESS;

var CLASS_BOOKING_REFUND_GET = "CLASS_BOOKING_REFUND_GET";

exports.CLASS_BOOKING_REFUND_GET = CLASS_BOOKING_REFUND_GET;

var CLASS_BOOKING_REFUND_POST = "CLASS_BOOKING_REFUND_POST";

exports.CLASS_BOOKING_REFUND_POST = CLASS_BOOKING_REFUND_POST;

var CLASS_EVALUATION_GET = "CLASS_EVALUATION_GET";

exports.CLASS_EVALUATION_GET = CLASS_EVALUATION_GET;

var CLASS_EVALUATION_POST = "CLASS_EVALUATION_POST";

exports.CLASS_EVALUATION_POST = CLASS_EVALUATION_POST;

var PERSONAL_LIST_GET = "PERSONAL_LIST_GET";

exports.PERSONAL_LIST_GET = PERSONAL_LIST_GET;

var PERSONAL_LIST_GET_LOADING = "PERSONAL_LIST_GET_LOADING";

exports.PERSONAL_LIST_GET_LOADING = PERSONAL_LIST_GET_LOADING;

var PERSONAL_LIST_GET_SUCCESS = "PERSONAL_LIST_GET_SUCCESS";

exports.PERSONAL_LIST_GET_SUCCESS = PERSONAL_LIST_GET_SUCCESS;

var PERSONAL_LIST_GET_FAILURE = "PERSONAL_LIST_GET_FAILURE";

exports.PERSONAL_LIST_GET_FAILURE = PERSONAL_LIST_GET_FAILURE;

var FETCH_PERSONAL_BOX_LIST = "FETCH_PERSONAL_BOX_LIST";

exports.FETCH_PERSONAL_BOX_LIST = FETCH_PERSONAL_BOX_LIST;

var PERSONAL_BOX_LIST_GET = "PERSONAL_BOX_LIST_GET";

exports.PERSONAL_BOX_LIST_GET = PERSONAL_BOX_LIST_GET;

var PERSONAL_BOX_LIST_GET_LOADING = "PERSONAL_BOX_LIST_GET_LOADING";

exports.PERSONAL_BOX_LIST_GET_LOADING = PERSONAL_BOX_LIST_GET_LOADING;

var PERSONAL_BOX_LIST_GET_SUCCESS = "PERSONAL_BOX_LIST_GET_SUCCESS";

exports.PERSONAL_BOX_LIST_GET_SUCCESS = PERSONAL_BOX_LIST_GET_SUCCESS;

var PERSONAL_BOX_LIST_GET_FAILURE = "PERSONAL_BOX_LIST_GET_FAILURE";

exports.PERSONAL_BOX_LIST_GET_FAILURE = PERSONAL_BOX_LIST_GET_FAILURE;

var FETCH_PERSONAL_CLASS_DETAIL = "FETCH_PERSONAL_CLASS_DETAIL";

exports.FETCH_PERSONAL_CLASS_DETAIL = FETCH_PERSONAL_CLASS_DETAIL;

var PERSONAL_CLASS_DETAIL_GET = "PERSONAL_CLASS_DETAIL_GET";

exports.PERSONAL_CLASS_DETAIL_GET = PERSONAL_CLASS_DETAIL_GET;

var PERSONAL_CLASS_DETAIL_GET_LOADING = "PERSONAL_CLASS_DETAIL_GET_LOADING";

exports.PERSONAL_CLASS_DETAIL_GET_LOADING = PERSONAL_CLASS_DETAIL_GET_LOADING;

var PERSONAL_CLASS_DETAIL_GET_SUCCESS = "PERSONAL_CLASS_DETAIL_GET_SUCCESS";

exports.PERSONAL_CLASS_DETAIL_GET_SUCCESS = PERSONAL_CLASS_DETAIL_GET_SUCCESS;

var PERSONAL_CLASS_DETAIL_GET_FAILURE = "PERSONAL_CLASS_DETAIL_GET_FAILURE";

exports.PERSONAL_CLASS_DETAIL_GET_FAILURE = PERSONAL_CLASS_DETAIL_GET_FAILURE;

var PERSONAL_BOOKING_INFO_GET = "PERSONAL_BOOKING_INFO_GET";

exports.PERSONAL_BOOKING_INFO_GET = PERSONAL_BOOKING_INFO_GET;

var PERSONAL_BOOKING_INFO_GET_LOADING = "PERSONAL_BOOKING_INFO_GET_LOADING";

exports.PERSONAL_BOOKING_INFO_GET_LOADING = PERSONAL_BOOKING_INFO_GET_LOADING;

var PERSONAL_BOOKING_INFO_GET_SUCCESS = "PERSONAL_BOOKING_INFO_GET_SUCCESS";

exports.PERSONAL_BOOKING_INFO_GET_SUCCESS = PERSONAL_BOOKING_INFO_GET_SUCCESS;

var PERSONAL_BOOKING_INFO_GET_FAILURE = "PERSONAL_BOOKING_INFO_GET_FAILURE";

exports.PERSONAL_BOOKING_INFO_GET_FAILURE = PERSONAL_BOOKING_INFO_GET_FAILURE;

var PERSONAL_PAY_SUBMIT = "PERSONAL_PAY_SUBMIT";

exports.PERSONAL_PAY_SUBMIT = PERSONAL_PAY_SUBMIT;

var PERSONAL_PAY_SUBMIT_LOADING = "PERSONAL_PAY_SUBMIT_LOADING";

exports.PERSONAL_PAY_SUBMIT_LOADING = PERSONAL_PAY_SUBMIT_LOADING;

var PERSONAL_PAY_SUBMIT_SUCCESS = "PERSONAL_PAY_SUBMIT_SUCCESS";

exports.PERSONAL_PAY_SUBMIT_SUCCESS = PERSONAL_PAY_SUBMIT_SUCCESS;

var PERSONAL_PAY_SUBMIT_FAILURE = "PERSONAL_PAY_SUBMIT_FAILURE";

exports.PERSONAL_PAY_SUBMIT_FAILURE = PERSONAL_PAY_SUBMIT_FAILURE;

var PERSONAL_BOOKING_SUCCESS_INFO_GET = "PERSONAL_BOOKING_SUCCESS_INFO_GET";

exports.PERSONAL_BOOKING_SUCCESS_INFO_GET = PERSONAL_BOOKING_SUCCESS_INFO_GET;

var PERSONAL_BOOKING_SUCCESS_INFO_GET_LOADING = "PERSONAL_BOOKING_SUCCESS_INFO_GET_LOADING";

exports.PERSONAL_BOOKING_SUCCESS_INFO_GET_LOADING = PERSONAL_BOOKING_SUCCESS_INFO_GET_LOADING;

var PERSONAL_BOOKING_SUCCESS_INFO_GET_SUCCESS = "PERSONAL_BOOKING_SUCCESS_INFO_GET_SUCCESS";

exports.PERSONAL_BOOKING_SUCCESS_INFO_GET_SUCCESS = PERSONAL_BOOKING_SUCCESS_INFO_GET_SUCCESS;

var PERSONAL_BOOKING_SUCCESS_INFO_GET_FAILURE = "PERSONAL_BOOKING_SUCCESS_INFO_GET_FAILURE";

exports.PERSONAL_BOOKING_SUCCESS_INFO_GET_FAILURE = PERSONAL_BOOKING_SUCCESS_INFO_GET_FAILURE;

var PERSONAL_BOOKING_DETAIL_GET = "PERSONAL_BOOKING_DETAIL_GET";

exports.PERSONAL_BOOKING_DETAIL_GET = PERSONAL_BOOKING_DETAIL_GET;

var PERSONAL_BOOKING_DETAIL_GET_LOADING = "PERSONAL_BOOKING_DETAIL_GET_LOADING";

exports.PERSONAL_BOOKING_DETAIL_GET_LOADING = PERSONAL_BOOKING_DETAIL_GET_LOADING;

var PERSONAL_BOOKING_DETAIL_GET_SUCCESS = "PERSONAL_BOOKING_DETAIL_GET_SUCCESS";

exports.PERSONAL_BOOKING_DETAIL_GET_SUCCESS = PERSONAL_BOOKING_DETAIL_GET_SUCCESS;

var PERSONAL_BOOKING_DETAIL_GET_FAILURE = "PERSONAL_BOOKING_DETAIL_GET_FAILURE";

exports.PERSONAL_BOOKING_DETAIL_GET_FAILURE = PERSONAL_BOOKING_DETAIL_GET_FAILURE;

var OLD_PERSONAL_BOOKING_DETAIL_GET = "OLD_PERSONAL_BOOKING_DETAIL_GET";

exports.OLD_PERSONAL_BOOKING_DETAIL_GET = OLD_PERSONAL_BOOKING_DETAIL_GET;

var OLD_PERSONAL_BOOKING_DETAIL_GET_LOADING = "OLD_PERSONAL_BOOKING_DETAIL_GET_LOADING";

exports.OLD_PERSONAL_BOOKING_DETAIL_GET_LOADING = OLD_PERSONAL_BOOKING_DETAIL_GET_LOADING;

var OLD_PERSONAL_BOOKING_DETAIL_GET_SUCCESS = "OLD_PERSONAL_BOOKING_DETAIL_GET_SUCCESS";

exports.OLD_PERSONAL_BOOKING_DETAIL_GET_SUCCESS = OLD_PERSONAL_BOOKING_DETAIL_GET_SUCCESS;

var OLD_PERSONAL_BOOKING_DETAIL_GET_FAILURE = "OLD_PERSONAL_BOOKING_DETAIL_GET_FAILURE";

exports.OLD_PERSONAL_BOOKING_DETAIL_GET_FAILURE = OLD_PERSONAL_BOOKING_DETAIL_GET_FAILURE;

var PERSONAL_REFUND_INFO_GET = "PERSONAL_REFUND_INFO_GET";

exports.PERSONAL_REFUND_INFO_GET = PERSONAL_REFUND_INFO_GET;

var PERSONAL_REFUND_INFO_GET_LOADING = "PERSONAL_REFUND_INFO_GET_LOADING";

exports.PERSONAL_REFUND_INFO_GET_LOADING = PERSONAL_REFUND_INFO_GET_LOADING;

var PERSONAL_REFUND_INFO_GET_SUCCESS = "PERSONAL_REFUND_INFO_GET_SUCCESS";

exports.PERSONAL_REFUND_INFO_GET_SUCCESS = PERSONAL_REFUND_INFO_GET_SUCCESS;

var PERSONAL_REFUND_INFO_GET_FAILURE = "PERSONAL_REFUND_INFO_GET_FAILURE";

exports.PERSONAL_REFUND_INFO_GET_FAILURE = PERSONAL_REFUND_INFO_GET_FAILURE;

var PERSONAL_REFUND_APPLY = "PERSONAL_REFUND_APPLY";

exports.PERSONAL_REFUND_APPLY = PERSONAL_REFUND_APPLY;

var PERSONAL_REFUND_APPLY_LOADING = "PERSONAL_REFUND_APPLY_LOADING";

exports.PERSONAL_REFUND_APPLY_LOADING = PERSONAL_REFUND_APPLY_LOADING;

var PERSONAL_REFUND_APPLY_SUCCESS = "PERSONAL_REFUND_APPLY_SUCCESS";

exports.PERSONAL_REFUND_APPLY_SUCCESS = PERSONAL_REFUND_APPLY_SUCCESS;

var PERSONAL_REFUND_APPLY_FAILURE = "PERSONAL_REFUND_APPLY_FAILURE";

exports.PERSONAL_REFUND_APPLY_FAILURE = PERSONAL_REFUND_APPLY_FAILURE;

var PERSONAL_RESERVE_ACCEPT = "PERSONAL_RESERVE_ACCEPT";

exports.PERSONAL_RESERVE_ACCEPT = PERSONAL_RESERVE_ACCEPT;

var PERSONAL_RESERVE_ACCEPT_SUCCESS = "PERSONAL_RESERVE_ACCEPT_SUCCESS";

exports.PERSONAL_RESERVE_ACCEPT_SUCCESS = PERSONAL_RESERVE_ACCEPT_SUCCESS;

var PERSONAL_RESERVE_REJECT = "PERSONAL_RESERVE_REJECT";

exports.PERSONAL_RESERVE_REJECT = PERSONAL_RESERVE_REJECT;

var PERSONAL_RESERVE_REJECT_SUCCESS = "PERSONAL_RESERVE_REJECT_SUCCESS";

exports.PERSONAL_RESERVE_REJECT_SUCCESS = PERSONAL_RESERVE_REJECT_SUCCESS;

var PERSONAL_RESERVE_CANCEL = "PERSONAL_RESERVE_CANCEL";

exports.PERSONAL_RESERVE_CANCEL = PERSONAL_RESERVE_CANCEL;

var PERSONAL_RESERVE_CANCEL_SUCCESS = "PERSONAL_RESERVE_CANCEL_SUCCESS";

exports.PERSONAL_RESERVE_CANCEL_SUCCESS = PERSONAL_RESERVE_CANCEL_SUCCESS;

var PERSONAL_RESERVE_VERIFY = "PERSONAL_RESERVE_VERIFY";

exports.PERSONAL_RESERVE_VERIFY = PERSONAL_RESERVE_VERIFY;

var PERSONAL_RESERVE_VERIFY_SUCCESS = "PERSONAL_RESERVE_VERIFY_SUCCESS";

exports.PERSONAL_RESERVE_VERIFY_SUCCESS = PERSONAL_RESERVE_VERIFY_SUCCESS;

var PERSONAL_TRAIN_LIST_GET = "PERSONAL_TRAIN_LIST_GET";

exports.PERSONAL_TRAIN_LIST_GET = PERSONAL_TRAIN_LIST_GET;

var PERSONAL_TRAIN_LIST_GET_SUCCESS = "PERSONAL_TRAIN_LIST_GET_SUCCESS";

exports.PERSONAL_TRAIN_LIST_GET_SUCCESS = PERSONAL_TRAIN_LIST_GET_SUCCESS;

var PERSONAL_CANCELED_TRAIN_LIST_GET = "PERSONAL_CANCELED_TRAIN_LIST_GET";

exports.PERSONAL_CANCELED_TRAIN_LIST_GET = PERSONAL_CANCELED_TRAIN_LIST_GET;

var PERSONAL_CANCELED_TRAIN_LIST_GET_SUCCESS = "PERSONAL_CANCELED_TRAIN_LIST_GET_SUCCESS";

exports.PERSONAL_CANCELED_TRAIN_LIST_GET_SUCCESS = PERSONAL_CANCELED_TRAIN_LIST_GET_SUCCESS;

var TRAIN_BOOKING_DATE_GET = "TRAIN_BOOKING_DATE_GET";

exports.TRAIN_BOOKING_DATE_GET = TRAIN_BOOKING_DATE_GET;

var TRAIN_BOOKING_DATE_GET_SUCCESS = "TRAIN_BOOKING_DATE_GET_SUCCESS";

exports.TRAIN_BOOKING_DATE_GET_SUCCESS = TRAIN_BOOKING_DATE_GET_SUCCESS;

var TRAIN_BOOKING_DATE_GET_LOADING = "TRAIN_BOOKING_DATE_GET_LOADING";

exports.TRAIN_BOOKING_DATE_GET_LOADING = TRAIN_BOOKING_DATE_GET_LOADING;

var TRAIN_BOOKING_DATE_GET_FAILURE = "TRAIN_BOOKING_DATE_GET_FAILURE";

exports.TRAIN_BOOKING_DATE_GET_FAILURE = TRAIN_BOOKING_DATE_GET_FAILURE;

var SUBMIT_TRAIN_BOOKING_DATE_GET = "SUBMIT_TRAIN_BOOKING_DATE_GET";

exports.SUBMIT_TRAIN_BOOKING_DATE_GET = SUBMIT_TRAIN_BOOKING_DATE_GET;

var SUBMIT_TRAIN_BOOKING_DATE_GET_SUCCESS = "SUBMIT_TRAIN_BOOKING_DATE_GET_SUCCESS";

exports.SUBMIT_TRAIN_BOOKING_DATE_GET_SUCCESS = SUBMIT_TRAIN_BOOKING_DATE_GET_SUCCESS;

var SUBMIT_TRAIN_BOOKING_DATE_GET_LOADING = "SUBMIT_TRAIN_BOOKING_DATE_GET_LOADING";

exports.SUBMIT_TRAIN_BOOKING_DATE_GET_LOADING = SUBMIT_TRAIN_BOOKING_DATE_GET_LOADING;

var SUBMIT_TRAIN_BOOKING_DATE_GET_FAILURE = "SUBMIT_TRAIN_BOOKING_DATE_GET_FAILURE";

exports.SUBMIT_TRAIN_BOOKING_DATE_GET_FAILURE = SUBMIT_TRAIN_BOOKING_DATE_GET_FAILURE;

var CAMP_LIST_GET = "CAMP_LIST_GET";

exports.CAMP_LIST_GET = CAMP_LIST_GET;

var CAMP_LIST_GET_SUCCESS = "CAMP_LIST_GET_SUCCESS";

exports.CAMP_LIST_GET_SUCCESS = CAMP_LIST_GET_SUCCESS;

var CAMP_DETAIL_GET = "CAMP_DETAIL_GET";

exports.CAMP_DETAIL_GET = CAMP_DETAIL_GET;

var CAMP_DETAIL_GET_SUCCESS = "CAMP_DETAIL_GET_SUCCESS";

exports.CAMP_DETAIL_GET_SUCCESS = CAMP_DETAIL_GET_SUCCESS;

var CAMP_SUBSCRIBE_GET = "CAMP_SUBSCRIBE_GET";

exports.CAMP_SUBSCRIBE_GET = CAMP_SUBSCRIBE_GET;

var CAMP_UNSUBSCRIBE_GET = "CAMP_UNSUBSCRIBE_GET";

exports.CAMP_UNSUBSCRIBE_GET = CAMP_UNSUBSCRIBE_GET;

var CAMP_BOOKING_CONFIRM_INFO_GET = "CAMP_BOOKING_CONFIRM_INFO_GET";

exports.CAMP_BOOKING_CONFIRM_INFO_GET = CAMP_BOOKING_CONFIRM_INFO_GET;

var CAMP_BOOKING_CONFIRM_INFO_GET_SUCCESS = "CAMP_BOOKING_CONFIRM_INFO_GET_SUCCESS";

exports.CAMP_BOOKING_CONFIRM_INFO_GET_SUCCESS = CAMP_BOOKING_CONFIRM_INFO_GET_SUCCESS;

var CAMP_BOOKING_CONFIRM_BALANCE_PAY_POST = "CAMP_BOOKING_CONFIRM_BALANCE_PAY_POST";

exports.CAMP_BOOKING_CONFIRM_BALANCE_PAY_POST = CAMP_BOOKING_CONFIRM_BALANCE_PAY_POST;

var CAMP_BOOKING_CONFIRM_BALANCE_PAY_POST_SUCCESS = "CAMP_BOOKING_CONFIRM_BALANCE_PAY_POST_SUCCESS";

exports.CAMP_BOOKING_CONFIRM_BALANCE_PAY_POST_SUCCESS = CAMP_BOOKING_CONFIRM_BALANCE_PAY_POST_SUCCESS;

var CAMP_BOOKING_CONFIRM_WX_PAY_POST = "CAMP_BOOKING_CONFIRM_WX_PAY_POST";

exports.CAMP_BOOKING_CONFIRM_WX_PAY_POST = CAMP_BOOKING_CONFIRM_WX_PAY_POST;

var CAMP_BOOKING_CONFIRM_WX_PAY_POST_SUCCESS = "CAMP_BOOKING_CONFIRM_WX_PAY_POST_SUCCESS";

exports.CAMP_BOOKING_CONFIRM_WX_PAY_POST_SUCCESS = CAMP_BOOKING_CONFIRM_WX_PAY_POST_SUCCESS;

var CAMP_REFUND_INFO_GET = "CAMP_REFUND_INFO_GET";

exports.CAMP_REFUND_INFO_GET = CAMP_REFUND_INFO_GET;

var CAMP_APPLY_REFUND_POST = "CAMP_APPLY_REFUND_POST";

exports.CAMP_APPLY_REFUND_POST = CAMP_APPLY_REFUND_POST;

var CAMP_BOOKING_DETAIL_GET = "CAMP_BOOKING_DETAIL_GET";

exports.CAMP_BOOKING_DETAIL_GET = CAMP_BOOKING_DETAIL_GET;

var CAMP_BOOKING_DETAIL_GET_SUCCESS = "CAMP_BOOKING_DETAIL_GET_SUCCESS";

exports.CAMP_BOOKING_DETAIL_GET_SUCCESS = CAMP_BOOKING_DETAIL_GET_SUCCESS;

var CAMP_BOOKING_SUCCESS_GET = "CAMP_BOOKING_SUCCESS_GET";

exports.CAMP_BOOKING_SUCCESS_GET = CAMP_BOOKING_SUCCESS_GET;

var BOX_CAMP_LIST_GET = "BOX_CAMP_LIST_GET";

exports.BOX_CAMP_LIST_GET = BOX_CAMP_LIST_GET;

var BOX_CAMP_LIST_GET_SUCCESS = "BOX_CAMP_LIST_GET_SUCCESS";

exports.BOX_CAMP_LIST_GET_SUCCESS = BOX_CAMP_LIST_GET_SUCCESS;

var GIVE_CLASS_RECEIVE_INFO_GET = "GIVE_CLASS_RECEIVE_INFO_GET";

exports.GIVE_CLASS_RECEIVE_INFO_GET = GIVE_CLASS_RECEIVE_INFO_GET;

var GIVE_CLASS_RECEIVE_INFO_GET_SUCCESS = "GIVE_CLASS_RECEIVE_INFO_GET_SUCCESS";

exports.GIVE_CLASS_RECEIVE_INFO_GET_SUCCESS = GIVE_CLASS_RECEIVE_INFO_GET_SUCCESS;

var GIVE_CLASS_CONFIRM_INFO_GET = "GIVE_CLASS_CONFIRM_INFO_GET";

exports.GIVE_CLASS_CONFIRM_INFO_GET = GIVE_CLASS_CONFIRM_INFO_GET;

var GIVE_CLASS_CONFIRM_INFO_GET_SUCCESS = "GIVE_CLASS_CONFIRM_INFO_GET_SUCCESS";

exports.GIVE_CLASS_CONFIRM_INFO_GET_SUCCESS = GIVE_CLASS_CONFIRM_INFO_GET_SUCCESS;

var GIVE_CLASS_DETAIL_GET = "GIVE_CLASS_DETAIL_GET";

exports.GIVE_CLASS_DETAIL_GET = GIVE_CLASS_DETAIL_GET;

var GIVE_CLASS_DETAIL_GET_SUCCESS = "GIVE_CLASS_DETAIL_GET_SUCCESS";

exports.GIVE_CLASS_DETAIL_GET_SUCCESS = GIVE_CLASS_DETAIL_GET_SUCCESS;

var GIVE_CLASS_BOOKING_DETAIL_GET = "GIVE_CLASS_BOOKING_DETAIL_GET";

exports.GIVE_CLASS_BOOKING_DETAIL_GET = GIVE_CLASS_BOOKING_DETAIL_GET;

var GIVE_CLASS_BOOKING_DETAIL_GET_SUCCESS = "GIVE_CLASS_BOOKING_DETAIL_GET_SUCCESS";

exports.GIVE_CLASS_BOOKING_DETAIL_GET_SUCCESS = GIVE_CLASS_BOOKING_DETAIL_GET_SUCCESS;

var GIVE_CLASS_REFUND_POST = "GIVE_CLASS_REFUND_POST";

exports.GIVE_CLASS_REFUND_POST = GIVE_CLASS_REFUND_POST;

var MY_GIVEN_LIST_GET = "MY_GIVEN_LIST_GET";

exports.MY_GIVEN_LIST_GET = MY_GIVEN_LIST_GET;

var MY_GIVEN_LIST_GET_SUCCESS = "MY_GIVEN_LIST_GET_SUCCESS";

exports.MY_GIVEN_LIST_GET_SUCCESS = MY_GIVEN_LIST_GET_SUCCESS;

var TRAINER_INDEX_GET = "TRAINER_INDEX_GET";

exports.TRAINER_INDEX_GET = TRAINER_INDEX_GET;

var TRAINER_INDEX_GET_SUCCESS = "TRAINER_INDEX_GET_SUCCESS";

exports.TRAINER_INDEX_GET_SUCCESS = TRAINER_INDEX_GET_SUCCESS;

var ONLINE_CAMP_TRAINER_LIST_GET = "ONLINE_CAMP_TRAINER_LIST_GET";

exports.ONLINE_CAMP_TRAINER_LIST_GET = ONLINE_CAMP_TRAINER_LIST_GET;

var ONLINE_CAMP_TRAINER_LIST_GET_SUCCESS = "ONLINE_CAMP_TRAINER_LIST_GET_SUCCESS";

exports.ONLINE_CAMP_TRAINER_LIST_GET_SUCCESS = ONLINE_CAMP_TRAINER_LIST_GET_SUCCESS;

var MY_BOOKING_INFO_GET = "MY_BOOKING_INFO_GET";

exports.MY_BOOKING_INFO_GET = MY_BOOKING_INFO_GET;

var MY_BOOKING_INFO_GET_LOADING = "MY_BOOKING_INFO_GET_LOADING";

exports.MY_BOOKING_INFO_GET_LOADING = MY_BOOKING_INFO_GET_LOADING;

var MY_BOOKING_INFO_GET_SUCCESS = "MY_BOOKING_INFO_GET_SUCCESS";

exports.MY_BOOKING_INFO_GET_SUCCESS = MY_BOOKING_INFO_GET_SUCCESS;

var MY_BOOKING_INFO_GET_FAILURE = "MY_BOOKING_INFO_GET_FAILURE";

exports.MY_BOOKING_INFO_GET_FAILURE = MY_BOOKING_INFO_GET_FAILURE;

var BOOKING_RECORDS_GET = "BOOKING_RECORDS_GET";

exports.BOOKING_RECORDS_GET = BOOKING_RECORDS_GET;

var BOOKING_RECORDS_GET_LOADING = "BOOKING_RECORDS_GET_LOADING";

exports.BOOKING_RECORDS_GET_LOADING = BOOKING_RECORDS_GET_LOADING;

var BOOKING_RECORDS_GET_SUCCESS = "BOOKING_RECORDS_GET_SUCCESS";

exports.BOOKING_RECORDS_GET_SUCCESS = BOOKING_RECORDS_GET_SUCCESS;

var BOOKING_RECORDS_GET_FAILURE = "BOOKING_RECORDS_GET_FAILURE";

exports.BOOKING_RECORDS_GET_FAILURE = BOOKING_RECORDS_GET_FAILURE;

var RECHARGE_CONFIRM_GET = "RECHARGE_CONFIRM_GET";

exports.RECHARGE_CONFIRM_GET = RECHARGE_CONFIRM_GET;

var RECHARGE_CONFIRM_GET_LOADING = "RECHARGE_CONFIRM_GET_LOADING";

exports.RECHARGE_CONFIRM_GET_LOADING = RECHARGE_CONFIRM_GET_LOADING;

var RECHARGE_CONFIRM_GET_SUCCESS = "RECHARGE_CONFIRM_GET_SUCCESS";

exports.RECHARGE_CONFIRM_GET_SUCCESS = RECHARGE_CONFIRM_GET_SUCCESS;

var RECHARGE_CONFIRM_GET_FAILURE = "RECHARGE_CONFIRM_GET_FAILURE";

exports.RECHARGE_CONFIRM_GET_FAILURE = RECHARGE_CONFIRM_GET_FAILURE;

var RECHARGE_ORDER_POST = "RECHARGE_ORDER_POST";

exports.RECHARGE_ORDER_POST = RECHARGE_ORDER_POST;

var RECHARGE_ORDER_POST_LOADING = "RECHARGE_ORDER_POST_LOADING";

exports.RECHARGE_ORDER_POST_LOADING = RECHARGE_ORDER_POST_LOADING;

var RECHARGE_ORDER_POST_SUCCESS = "RECHARGE_ORDER_POST_SUCCESS";

exports.RECHARGE_ORDER_POST_SUCCESS = RECHARGE_ORDER_POST_SUCCESS;

var RECHARGE_ORDER_POST_FAILURE = "RECHARGE_ORDER_POST_FAILURE";

exports.RECHARGE_ORDER_POST_FAILURE = RECHARGE_ORDER_POST_FAILURE;

var MY_INFO_GET = "MY_INFO_GET";

exports.MY_INFO_GET = MY_INFO_GET;

var MY_INFO_GET_SUCCESS = "MY_INFO_GET_SUCCESS";

exports.MY_INFO_GET_SUCCESS = MY_INFO_GET_SUCCESS;

var MY_INFO_GET_LOADING = "MY_INFO_GET_LOADING";

exports.MY_INFO_GET_LOADING = MY_INFO_GET_LOADING;

var MY_INFO_GET_FAILURE = "MY_INFO_GET_FAILURE";

exports.MY_INFO_GET_FAILURE = MY_INFO_GET_FAILURE;

var USER_EXT_GET = "USER_EXT_GET";

exports.USER_EXT_GET = USER_EXT_GET;

var USER_EXT_GET_LOADING = "USER_EXT_GET_LOADING";

exports.USER_EXT_GET_LOADING = USER_EXT_GET_LOADING;

var USER_EXT_GET_SUCCESS = "USER_EXT_GET_SUCCESS";

exports.USER_EXT_GET_SUCCESS = USER_EXT_GET_SUCCESS;

var USER_EXT_GET_FAILURE = "USER_EXT_GET_FAILURE";

exports.USER_EXT_GET_FAILURE = USER_EXT_GET_FAILURE;

var USER_EXT_POST = "USER_EXT_POST";

exports.USER_EXT_POST = USER_EXT_POST;

var USER_EXT_POST_LOADING = "USER_EXT_POST_LOADING";

exports.USER_EXT_POST_LOADING = USER_EXT_POST_LOADING;

var USER_EXT_POST_SUCCESS = "USER_EXT_POST_SUCCESS";

exports.USER_EXT_POST_SUCCESS = USER_EXT_POST_SUCCESS;

var USER_EXT_POST_FAILURE = "USER_EXT_POST_FAILURE";

exports.USER_EXT_POST_FAILURE = USER_EXT_POST_FAILURE;

var VIP_DETAIL_INFO_GET = "VIP_DETAIL_INFO_GET";

exports.VIP_DETAIL_INFO_GET = VIP_DETAIL_INFO_GET;

var VIP_DETAIL_INFO_GET_LOADING = "VIP_DETAIL_INFO_GET_LOADING";

exports.VIP_DETAIL_INFO_GET_LOADING = VIP_DETAIL_INFO_GET_LOADING;

var VIP_DETAIL_INFO_GET_SUCCESS = "VIP_DETAIL_INFO_GET_SUCCESS";

exports.VIP_DETAIL_INFO_GET_SUCCESS = VIP_DETAIL_INFO_GET_SUCCESS;

var VIP_DETAIL_INFO_GET_FAILURE = "VIP_DETAIL_INFO_GET_FAILURE";

exports.VIP_DETAIL_INFO_GET_FAILURE = VIP_DETAIL_INFO_GET_FAILURE;

var SUPER_CHANGE_RECORDS_GET = "SUPER_CHANGE_RECORDS_GET";

exports.SUPER_CHANGE_RECORDS_GET = SUPER_CHANGE_RECORDS_GET;

var SUPER_CHANGE_RECORDS_GET_LOADING = "SUPER_CHANGE_RECORDS_GET_LOADING";

exports.SUPER_CHANGE_RECORDS_GET_LOADING = SUPER_CHANGE_RECORDS_GET_LOADING;

var SUPER_CHANGE_RECORDS_GET_SUCCESS = "SUPER_CHANGE_RECORDS_GET_SUCCESS";

exports.SUPER_CHANGE_RECORDS_GET_SUCCESS = SUPER_CHANGE_RECORDS_GET_SUCCESS;

var SUPER_CHANGE_RECORDS_GET_FAILURE = "SUPER_CHANGE_RECORDS_GET_FAILURE";

exports.SUPER_CHANGE_RECORDS_GET_FAILURE = SUPER_CHANGE_RECORDS_GET_FAILURE;

var ONLINE_CAMP_HOME_DATA_GET = "ONLINE_CAMP_HOME_DATA_GET";

exports.ONLINE_CAMP_HOME_DATA_GET = ONLINE_CAMP_HOME_DATA_GET;

var ONLINE_CAMP_HOME_DATA_GET_SUCCESS = "ONLINE_CAMP_HOME_DATA_GET_SUCCESS";

exports.ONLINE_CAMP_HOME_DATA_GET_SUCCESS = ONLINE_CAMP_HOME_DATA_GET_SUCCESS;

var ONLINE_COURSE_LIST_GET = "ONLINE_COURSE_LIST_GET";

exports.ONLINE_COURSE_LIST_GET = ONLINE_COURSE_LIST_GET;

var ONLINE_COURSE_LIST_GET_SUCCESS = "ONLINE_COURSE_LIST_GET_SUCCESS";

exports.ONLINE_COURSE_LIST_GET_SUCCESS = ONLINE_COURSE_LIST_GET_SUCCESS;

var ONLINE_CAMP_LIST_GET = "ONLINE_CAMP_LIST_GET";

exports.ONLINE_CAMP_LIST_GET = ONLINE_CAMP_LIST_GET;

var ONLINE_CAMP_LIST_GET_SUCCESS = "ONLINE_CAMP_LIST_GET_SUCCESS";

exports.ONLINE_CAMP_LIST_GET_SUCCESS = ONLINE_CAMP_LIST_GET_SUCCESS;

var ONLINE_CAMP_DETAIL_GET = "ONLINE_CAMP_DETAIL_GET";

exports.ONLINE_CAMP_DETAIL_GET = ONLINE_CAMP_DETAIL_GET;

var ONLINE_CAMP_DETAIL_GET_SUCCESS = "ONLINE_CAMP_DETAIL_GET_SUCCESS";

exports.ONLINE_CAMP_DETAIL_GET_SUCCESS = ONLINE_CAMP_DETAIL_GET_SUCCESS;

var ONLINE_CAMP_DETAIL_SCHEDULE_GET = "ONLINE_CAMP_DETAIL_SCHEDULE_GET";

exports.ONLINE_CAMP_DETAIL_SCHEDULE_GET = ONLINE_CAMP_DETAIL_SCHEDULE_GET;

var ONLINE_CAMP_DETAIL_SCHEDULE_GET_SUCCESS = "ONLINE_CAMP_DETAIL_SCHEDULE_GET_SUCCESS";

exports.ONLINE_CAMP_DETAIL_SCHEDULE_GET_SUCCESS = ONLINE_CAMP_DETAIL_SCHEDULE_GET_SUCCESS;

var MY_TICKETS_GET = "MY_TICKETS_GET";

exports.MY_TICKETS_GET = MY_TICKETS_GET;

var MY_TICKETS_GET_SUCCESS = "MY_TICKETS_GET_SUCCESS";

exports.MY_TICKETS_GET_SUCCESS = MY_TICKETS_GET_SUCCESS;

var INVALID_TICKETS_GET = "INVALID_TICKETS_GET";

exports.INVALID_TICKETS_GET = INVALID_TICKETS_GET;

var INVALID_TICKETS_GET_SUCCESS = "INVALID_TICKETS_GET_SUCCESS";

exports.INVALID_TICKETS_GET_SUCCESS = INVALID_TICKETS_GET_SUCCESS;

var EXCHANGE_TICKET_CODE_POST = "EXCHANGE_TICKET_CODE_POST";

exports.EXCHANGE_TICKET_CODE_POST = EXCHANGE_TICKET_CODE_POST;

var PAY_SUCCESS_RECEIPT = "PAY_SUCCESS_RECEIPT";

exports.PAY_SUCCESS_RECEIPT = PAY_SUCCESS_RECEIPT;

var PAY_FAILURE_RECEIPT = "PAY_FAILURE_RECEIPT";

exports.PAY_FAILURE_RECEIPT = PAY_FAILURE_RECEIPT;

var PHONE_CODE_GET = "PHONE_CODE_GET";

exports.PHONE_CODE_GET = PHONE_CODE_GET;

var BIND_PHONE_BY_WX_GET = "BIND_PHONE_BY_WX_GET";

exports.BIND_PHONE_BY_WX_GET = BIND_PHONE_BY_WX_GET;

var BIND_PHONE_POST = "BIND_PHONE_POST";

exports.BIND_PHONE_POST = BIND_PHONE_POST;

var NOTICE_LIST_GET = "NOTICE_LIST_GET";

exports.NOTICE_LIST_GET = NOTICE_LIST_GET;

var MESSAGE_MANAGE_LIST_GET = "MESSAGE_MANAGE_LIST_GET";

exports.MESSAGE_MANAGE_LIST_GET = MESSAGE_MANAGE_LIST_GET;

var MESSAGE_MANAGE_LIST_GET_SUCCESS = "MESSAGE_MANAGE_LIST_GET_SUCCESS";

exports.MESSAGE_MANAGE_LIST_GET_SUCCESS = MESSAGE_MANAGE_LIST_GET_SUCCESS;

var SUBSCRIBE_MESSAGE_POST = "SUBSCRIBE_MESSAGE_POST";

exports.SUBSCRIBE_MESSAGE_POST = SUBSCRIBE_MESSAGE_POST;

var SUBSCRIBE_MESSAGE_POST_SUCCESS = "SUBSCRIBE_MESSAGE_POST_SUCCESS";

exports.SUBSCRIBE_MESSAGE_POST_SUCCESS = SUBSCRIBE_MESSAGE_POST_SUCCESS;

var ORDER_MESSAGE_LIST_GET = "ORDER_MESSAGE_LIST_GET";

exports.ORDER_MESSAGE_LIST_GET = ORDER_MESSAGE_LIST_GET;

var ORDER_MESSAGE_LIST_GET_SUCCESS = "ORDER_MESSAGE_LIST_GET_SUCCESS";

exports.ORDER_MESSAGE_LIST_GET_SUCCESS = ORDER_MESSAGE_LIST_GET_SUCCESS;

var SUBSCRIBE_EVENT_POST = "SUBSCRIBE_EVENT_POST";

exports.SUBSCRIBE_EVENT_POST = SUBSCRIBE_EVENT_POST;

var SUBSCRIBE_EVENT_POST_SUCCESS = "SUBSCRIBE_EVENT_POST_SUCCESS";

exports.SUBSCRIBE_EVENT_POST_SUCCESS = SUBSCRIBE_EVENT_POST_SUCCESS;

var SUPER_RANK_GET = "SUPER_RANK_GET";

exports.SUPER_RANK_GET = SUPER_RANK_GET;

var SUPER_RANK_GET_SUCCESS = "SUPER_RANK_GET_SUCCESS";

exports.SUPER_RANK_GET_SUCCESS = SUPER_RANK_GET_SUCCESS;

var SUPER_RANK_POSTER_GET = "SUPER_RANK_POSTER_GET";

exports.SUPER_RANK_POSTER_GET = SUPER_RANK_POSTER_GET;

var GROUP_RANK_GET = "GROUP_RANK_GET";

exports.GROUP_RANK_GET = GROUP_RANK_GET;

var GROUP_RANK_GET_SUCCESS = "GROUP_RANK_GET_SUCCESS";

exports.GROUP_RANK_GET_SUCCESS = GROUP_RANK_GET_SUCCESS;

var WXPAY_ORDER_LIST_GET = "WXPAY_ORDER_LIST_GET";

exports.WXPAY_ORDER_LIST_GET = WXPAY_ORDER_LIST_GET;

var WXPAY_ORDER_LIST_GET_SUCCESS = "WXPAY_ORDER_LIST_GET_SUCCESS";

exports.WXPAY_ORDER_LIST_GET_SUCCESS = WXPAY_ORDER_LIST_GET_SUCCESS;

var WXPAY_ORDER_LIST_INVOICE_GET = "WXPAY_ORDER_LIST_INVOICE_GET";

exports.WXPAY_ORDER_LIST_INVOICE_GET = WXPAY_ORDER_LIST_INVOICE_GET;

var WXPAY_ORDER_LIST_INVOICE_GET_SUCCESS = "WXPAY_ORDER_LIST_INVOICE_GET_SUCCESS";

exports.WXPAY_ORDER_LIST_INVOICE_GET_SUCCESS = WXPAY_ORDER_LIST_INVOICE_GET_SUCCESS;

var WXPAY_INVOICE_HISTORY_GET = "WXPAY_INVOICE_HISTORY_GET";

exports.WXPAY_INVOICE_HISTORY_GET = WXPAY_INVOICE_HISTORY_GET;

var WXPAY_INVOICE_HISTORY_GET_SUCCESS = "WXPAY_INVOICE_HISTORY_GET_SUCCESS";

exports.WXPAY_INVOICE_HISTORY_GET_SUCCESS = WXPAY_INVOICE_HISTORY_GET_SUCCESS;

var INVOICE_BLUE_SUBMIT = "INVOICE_BLUE_SUBMIT";

exports.INVOICE_BLUE_SUBMIT = INVOICE_BLUE_SUBMIT;

var INVOICE_BLUE_SUBMIT_SUCCESS = "INVOICE_BLUE_SUBMIT_SUCCESS";

exports.INVOICE_BLUE_SUBMIT_SUCCESS = INVOICE_BLUE_SUBMIT_SUCCESS;

var INVOICE_BLUE_SUBMIT_FAILURE = "INVOICE_BLUE_SUBMIT_FAILURE";

exports.INVOICE_BLUE_SUBMIT_FAILURE = INVOICE_BLUE_SUBMIT_FAILURE;

var PICTURE_SHARE_URL_GET = "PICTURE_SHARE_URL_GET";

exports.PICTURE_SHARE_URL_GET = PICTURE_SHARE_URL_GET;

var PICTURE_SHARE_URL_GET_LOADING = "PICTURE_SHARE_URL_GET_LOADING";

exports.PICTURE_SHARE_URL_GET_LOADING = PICTURE_SHARE_URL_GET_LOADING;

var PICTURE_SHARE_URL_GET_SUCCESS = "PICTURE_SHARE_URL_GET_SUCCESS";

exports.PICTURE_SHARE_URL_GET_SUCCESS = PICTURE_SHARE_URL_GET_SUCCESS;

var PICTURE_SHARE_URL_GET_FAILURE = "PICTURE_SHARE_URL_GET_FAILURE";

exports.PICTURE_SHARE_URL_GET_FAILURE = PICTURE_SHARE_URL_GET_FAILURE;

var BADGE_INFO_GET = "BADGE_INFO_GET";

exports.BADGE_INFO_GET = BADGE_INFO_GET;

var BADGE_INFO_GET_SUCCESS = "BADGE_INFO_GET_SUCCESS";

exports.BADGE_INFO_GET_SUCCESS = BADGE_INFO_GET_SUCCESS;

var BADGE_INFO_GET_LOADING = "BADGE_INFO_GET_LOADING";

exports.BADGE_INFO_GET_LOADING = BADGE_INFO_GET_LOADING;

var BADGE_INFO_GET_FAILURE = "BADGE_INFO_GET_FAILURE";

exports.BADGE_INFO_GET_FAILURE = BADGE_INFO_GET_FAILURE;

var BADGE_DETAIL_GET = "BADGE_DETAIL_GET";

exports.BADGE_DETAIL_GET = BADGE_DETAIL_GET;

var BADGE_DETAIL_GET_SUCCESS = "BADGE_DETAIL_GET_SUCCESS";

exports.BADGE_DETAIL_GET_SUCCESS = BADGE_DETAIL_GET_SUCCESS;

var BADGE_DETAIL_GET_LOADING = "BADGE_DETAIL_GET_LOADING";

exports.BADGE_DETAIL_GET_LOADING = BADGE_DETAIL_GET_LOADING;

var BADGE_DETAIL_GET_FAILURE = "BADGE_DETAIL_GET_FAILURE";

exports.BADGE_DETAIL_GET_FAILURE = BADGE_DETAIL_GET_FAILURE;

var BADGE_USER_LIST_GET = "BADGE_USER_LIST_GET";

exports.BADGE_USER_LIST_GET = BADGE_USER_LIST_GET;

var BADGE_USER_LIST_GET_SUCCESS = "BADGE_USER_LIST_GET_SUCCESS";

exports.BADGE_USER_LIST_GET_SUCCESS = BADGE_USER_LIST_GET_SUCCESS;

var BADGE_USER_LIST_GET_LOADING = "BADGE_USER_LIST_GET_LOADING";

exports.BADGE_USER_LIST_GET_LOADING = BADGE_USER_LIST_GET_LOADING;

var BADGE_USER_LIST_GET_FAILURE = "BADGE_USER_LIST_GET_FAILURE";

exports.BADGE_USER_LIST_GET_FAILURE = BADGE_USER_LIST_GET_FAILURE;

var SUPERALLIANCETICKET_IDENTITY_GET = "SUPERALLIANCETICKET_IDENTITY_GET";

exports.SUPERALLIANCETICKET_IDENTITY_GET = SUPERALLIANCETICKET_IDENTITY_GET;

var SUPERALLIANCETICKET_CODE_POST = "SUPERALLIANCETICKET_CODE_POST";

exports.SUPERALLIANCETICKET_CODE_POST = SUPERALLIANCETICKET_CODE_POST;

var SUPERALLIANCETICKET_IDENTITY_GET_LOADING = "SUPERALLIANCETICKET_IDENTITY_GET_LOADING";

exports.SUPERALLIANCETICKET_IDENTITY_GET_LOADING = SUPERALLIANCETICKET_IDENTITY_GET_LOADING;

var SUPERALLIANCETICKET_IDENTITY_GET_SUCCESS = "SUPERALLIANCETICKET_IDENTITY_GET_SUCCESS";

exports.SUPERALLIANCETICKET_IDENTITY_GET_SUCCESS = SUPERALLIANCETICKET_IDENTITY_GET_SUCCESS;

var SUPERALLIANCETICKET_IDENTITY_GET_FAILURE = "SUPERALLIANCETICKET_IDENTITY_GET_FAILURE";

exports.SUPERALLIANCETICKET_IDENTITY_GET_FAILURE = SUPERALLIANCETICKET_IDENTITY_GET_FAILURE;

var BALANCE_RECORDS_GET = "BALANCE_RECORDS_GET";

exports.BALANCE_RECORDS_GET = BALANCE_RECORDS_GET;

var BALANCE_RECORDS_GET_LOADING = "BALANCE_RECORDS_GET_LOADING";

exports.BALANCE_RECORDS_GET_LOADING = BALANCE_RECORDS_GET_LOADING;

var BALANCE_RECORDS_GET_SUCCESS = "BALANCE_RECORDS_GET_SUCCESS";

exports.BALANCE_RECORDS_GET_SUCCESS = BALANCE_RECORDS_GET_SUCCESS;

var BALANCE_RECORDS_GET_FAILURE = "BALANCE_RECORDS_GET_FAILURE";

exports.BALANCE_RECORDS_GET_FAILURE = BALANCE_RECORDS_GET_FAILURE;

var CARD_RETURN_SUBMIT = "CARD_RETURN_SUBMIT";

exports.CARD_RETURN_SUBMIT = CARD_RETURN_SUBMIT;

var CARD_RETURN_SUBMIT_LOADING = "CARD_RETURN_SUBMIT_LOADING";

exports.CARD_RETURN_SUBMIT_LOADING = CARD_RETURN_SUBMIT_LOADING;

var CARD_RETURN_SUBMIT_SUCCESS = "CARD_RETURN_SUBMIT_SUCCESS";

exports.CARD_RETURN_SUBMIT_SUCCESS = CARD_RETURN_SUBMIT_SUCCESS;

var CARD_RETURN_SUBMIT_FAILURE = "CARD_RETURN_SUBMIT_FAILURE";

exports.CARD_RETURN_SUBMIT_FAILURE = CARD_RETURN_SUBMIT_FAILURE;

var CARD_RETURN_CANCEL = "CARD_RETURN_CANCEL";

exports.CARD_RETURN_CANCEL = CARD_RETURN_CANCEL;

var CARD_RETURN_CANCEL_LOADING = "CARD_RETURN_CANCEL_LOADING";

exports.CARD_RETURN_CANCEL_LOADING = CARD_RETURN_CANCEL_LOADING;

var CARD_RETURN_CANCEL_SUCCESS = "CARD_RETURN_CANCEL_SUCCESS";

exports.CARD_RETURN_CANCEL_SUCCESS = CARD_RETURN_CANCEL_SUCCESS;

var CARD_RETURN_CANCEL_FAILURE = "CARD_RETURN_CANCEL_FAILURE";

exports.CARD_RETURN_CANCEL_FAILURE = CARD_RETURN_CANCEL_FAILURE;

var OPTION_LIST_GET = "OPTION_LIST_GET";

exports.OPTION_LIST_GET = OPTION_LIST_GET;

var OPTION_LIST_GET_LOADING = "OPTION_LIST_GET_LOADING";

exports.OPTION_LIST_GET_LOADING = OPTION_LIST_GET_LOADING;

var OPTION_LIST_GET_SUCCESS = "OPTION_LIST_GET_SUCCESS";

exports.OPTION_LIST_GET_SUCCESS = OPTION_LIST_GET_SUCCESS;

var OPTION_LIST_GET_FAILURE = "OPTION_LIST_GET_FAILURE";

exports.OPTION_LIST_GET_FAILURE = OPTION_LIST_GET_FAILURE;

var CONFIRM_MODAL_POST = "CONFIRM_MODAL_POST";

exports.CONFIRM_MODAL_POST = CONFIRM_MODAL_POST;

var NOVICE_CLASS_LIST_GET = "NOVICE_CLASS_LIST_GET";

exports.NOVICE_CLASS_LIST_GET = NOVICE_CLASS_LIST_GET;

var NOVICE_CLASS_LIST_GET_SUCCESS = "NOVICE_CLASS_LIST_GET_SUCCESS";

exports.NOVICE_CLASS_LIST_GET_SUCCESS = NOVICE_CLASS_LIST_GET_SUCCESS;