Object.defineProperty(exports, "__esModule", {
    value: !0
}), Object.defineProperty(exports, "PERSIST_RESUME_PUT", {
    enumerable: !0,
    get: function() {
        return _types.PERSIST_RESUME_PUT;
    }
}), Object.defineProperty(exports, "COOKIE_PUT", {
    enumerable: !0,
    get: function() {
        return _types.COOKIE_PUT;
    }
}), Object.defineProperty(exports, "SYSTEMINFO_PUT", {
    enumerable: !0,
    get: function() {
        return _types.SYSTEMINFO_PUT;
    }
}), Object.defineProperty(exports, "LOGININFO_PUT", {
    enumerable: !0,
    get: function() {
        return _types.LOGININFO_PUT;
    }
}), exports.TRAINER_SCHEDULE_IDS_PUT = exports.BOX_CAMPS_PUT = exports.CAMPS_SMALL_PUT = exports.BOX_CAMPS_LIST_PUT = exports.CAMP_BOOKING_DETAIL_PUT = exports.NEW_CAMP_STATUS_ON_CAMP_PUT = exports.CITY_NEW_CAMP_SHOW_STATUS_ON_NAV_BAR_PUT = exports.CAMP_BOOKING_CONFIRM_INFO_PUT = exports.OFFLINE_CAMP_SCHEDULE_SHOW_APPLICABLE = exports.CAMP_SUBSCRIBE_PUT = exports.CAMP_DETAIL_PUT = exports.CAMP_LIST_CITY_PUT = exports.CAMPS_LIST_PUT = exports.PERSONAL_CANCELED_TRAIN_LIST_PUT = exports.PERSONAL_TRAIN_LIST_PUT = exports.TRAIN_BOOKING_DATE_PUT = exports.TRAINER_PERSONAL_LIST_PUT = exports.OLD_PERSONAL_BOOKING_DETAIL_PUT = exports.PERSONAL_BOOKING_SUCCESS_INFO_PUT = exports.PERSONAL_BOOKING_DETAIL_PUT = exports.PERSONAL_BOOKING_INFO_PUT = exports.PERSONAL_CLASS_DETAIL_PUT = exports.PERSONAL_BOX_LIST_PUT = exports.PERSONAL_LIST_PUT = exports.CLASS_BOOKING_DETAIL_PUT = exports.CLASS_BOOKING_SUCCESS_PUT = exports.CLASS_BOOKING_CONFIRM_PUT = exports.CLASS_DETAIL_PUT = exports.CLASS_LIST_TRAINER_BOXIDS_PUT = exports.CLASS_LIST_TRAINER_DATES_PUT = exports.CLASS_LIST_TRAINER_TIME_PUT = exports.CLASS_BOX_ID_PUT = exports.CLASS_BOX_DATES_PUT = exports.CLASS_BOX_TIME_PUT = exports.CLASS_SCHEDULES_SUBSCRIBE_PUT = exports.CLASS_CATEGORY_FILTER_PUT = exports.CLASS_BOX_FILTER_PUT = exports.CLASS_SCHEDULES_TIME_PUT = exports.CLASS_CONTENT_DATES_PUT = exports.CLASS_CONTENT_CITY_PUT = exports.BOX_BOOKING_DETAIL_PUT = exports.BOX_BOOKING_CONFIRM_INFO_PUT = exports.BOX_NAME_PUT = exports.BOX_LIST_PUT = exports.CLASS_PRICE_MAP_PUT = exports.DATE_BOX_SCHEDULES_MAP_PUT = exports.BOX_EXTRA_MAP_PUT = exports.VIP_TASK_MAP_PUT = exports.VIP_EQUITY_MAP_PUT = exports.VIP_LEVEL_CONFIG_MAP_PUT = exports.POSITION_SORTED_RELATE_MAP_PUT = exports.POSITION_RELATE_MAP_PUT = exports.PROMOTION_POSITION_RELATE_MAP_PUT = exports.PROMOTION_MAP_PUT = exports.POSITION_RULES_MAP_PUT = exports.POSITION_MAP_PUT = exports.ONLINE_CAMP_TRAINER_LIST_PUT = exports.TRAINER_SMALL_MAP_PUT = exports.TRAINER_MAP_PUT = exports.BOX_SMALL_MAP_PUT = exports.BOX_MAP_PUT = exports.PERSONAL_MAP_PUT = exports.PERSONAL_SCHEDULE_MAP_PUT = exports.PERSONAL_CAMP_MAP_PUT = exports.CAMP_MAP_PUT = exports.SCHEDULE_SMALL_MAP_PUT = exports.SCHEDULE_MAP_PUT = exports.CLASS_SMALL_MAP_PUT = exports.CLASS_MAP_PUT = exports.MESSAGE_MAP_COUNT_PUT = exports.ORDER_MESSAGES_PUT = exports.USER_SUBSCRIBE_MAP_PUT = exports.MESSAGE_SUBSCRIBE_LIST_PUT = exports.RECHARGE_AB_CATEGORY_PUT = exports.HAS_SHOWED_TOOLTIP_PUT = exports.NEWER_GUIDE_USER_PUT = exports.PERSONAL_EXPIRE_NUMBER_PUT = exports.MY_INVITE_INFO_NUMBER_PUT = exports.NEW_BADGE_NUMBER_PUT = exports.ALL_TICKET_VALUE_PUT = exports.NEW_TICKET_NUMBER_PUT = exports.EXPIRE_TICKET_NUMBER_PUT = exports.AFTER_SHARE_PROMPT_PUT = exports.BIND_PHONE_NUMBER_PUT = exports.SUBSCRIBE_SCHEDULE_PUT = exports.NOVICE_PUT = exports.NEWER_PUT = exports.NEW_USER_BONUS_PUT = exports.WECHAT_SUBSCRIBE_PUT = exports.UNREGISTERED_PUT = exports.USER_EXT_STATE_PUT = exports.EXTERNAL_INVITER_PUT = exports.CITY_LIST_PUT = exports.CITY_LOCATION_PUT = exports.CITY_CURRENT_PUT = exports.BOOKING_CONFIRM_MODAL_PUT = exports.USER_VIP_PUT = exports.USER_INVITER_INFO_PUT = exports.USER_DISCOUNT_INFO_PUT = exports.MODEL_PUT = void 0, 
exports.NOVICE_CLASS_LIST_PUT = exports.NOVICE_CLASS_MAP_PUT = exports.SCORE_LIST_PUT = exports.REASON_LIST_PUT = exports.BALANCE_CLEAR_PUT = exports.BALANCE_INFO_PUT = exports.BALANCE_RECORDS_PUT = exports.WXPAY_INVOICE_HISTORY_PUT = exports.INVOICE_ORDER_TYPE_PUT = exports.WXPAY_ORDER_LIST_INVOICE_PUT = exports.WXPAY_ORDER_LIST_PUT = exports.SUPERALLIANCETICKET_IDENTITY_PUT = exports.PICTURE_SHARE_URL_PUT = exports.BADGE_USER_LIST_PUT = exports.BADGE_DETAIL_PUT = exports.BADGE_INFO_PUT = exports.APP_CLASS_TYPE_PUT = exports.ONLINE_CAMP_FIRST_SHOW_SELECT_SCHEDULE_MODAL_STATE = exports.ONLINE_CAMP_SCHEDULE_SELECTED_SCHEDULE = exports.ONLINE_CAMP_SCHEDULE_SELECTED_CITY = exports.ONLINE_CAMP_SCHEDULE_SHOW_APPLICABLE = exports.ONLINE_CAMP_DETAIL_SCHEDULE_PUT = exports.ONLINE_CAMP_DETAIL_PUT = exports.ONLINE_CAMP_LIST_PUT = exports.ONLINE_COURSE_LIST_PUT = exports.ONLINE_CAMP_SCHEDULE_MAP_PUT = exports.ONLINE_CAMP_HOME_DATA_PUT = exports.INVALID_TICKETS_PUT = exports.MY_TICKETS_PUT = exports.GROUP_RANK_MAP_PUT = exports.SUPER_RANK_MAP_PUT = exports.SUPER_CHANGE_RECORDS_PUT = exports.VIP_DETAIL_INFO_PUT = exports.USER_EXT_PUT = exports.MY_INFO_PUT = exports.RECHARGE_CONFIRM_PUT = exports.BOOKING_RECORDS_PUT = exports.MY_BOOKING_INFO_PUT = exports.TRAINER_PROFILE_PUT = exports.GIVE_CLASS_BALANCE_PAY_PUT = exports.GIVE_CLASS_DETAIL_PUT = exports.GIVE_CLASS_BOOKING_DETAIL_PUT = exports.GIVE_CLASS_RECEIVE_PUT = exports.GIVE_CONFIRM_BOOKING_CONFIRM_INFO_PUT = exports.MY_GIVEN_LIST_PUT = void 0;

var _types = require("./../../imports/types.js"), MODEL_PUT = "model/PUT";

exports.MODEL_PUT = MODEL_PUT;

var USER_DISCOUNT_INFO_PUT = "user/discount/PUT";

exports.USER_DISCOUNT_INFO_PUT = USER_DISCOUNT_INFO_PUT;

var USER_INVITER_INFO_PUT = "user/inviter/PUT";

exports.USER_INVITER_INFO_PUT = USER_INVITER_INFO_PUT;

var USER_VIP_PUT = "user/vip/PUT";

exports.USER_VIP_PUT = USER_VIP_PUT;

var BOOKING_CONFIRM_MODAL_PUT = "booking/confirm/modal/PUT";

exports.BOOKING_CONFIRM_MODAL_PUT = BOOKING_CONFIRM_MODAL_PUT;

var CITY_CURRENT_PUT = "city/current/PUT";

exports.CITY_CURRENT_PUT = CITY_CURRENT_PUT;

var CITY_LOCATION_PUT = "city/location/PUT";

exports.CITY_LOCATION_PUT = CITY_LOCATION_PUT;

var CITY_LIST_PUT = "city/list/PUT";

exports.CITY_LIST_PUT = CITY_LIST_PUT;

var EXTERNAL_INVITER_PUT = "external/inviter/PUT";

exports.EXTERNAL_INVITER_PUT = EXTERNAL_INVITER_PUT;

var USER_EXT_STATE_PUT = "user/extState/PUT";

exports.USER_EXT_STATE_PUT = USER_EXT_STATE_PUT;

var UNREGISTERED_PUT = "user/extState/isUnregistered/PUT";

exports.UNREGISTERED_PUT = UNREGISTERED_PUT;

var WECHAT_SUBSCRIBE_PUT = "user/extState/wechatSubscribe/PUT";

exports.WECHAT_SUBSCRIBE_PUT = WECHAT_SUBSCRIBE_PUT;

var NEW_USER_BONUS_PUT = "user/extState/isGetNewUserBonus/PUT";

exports.NEW_USER_BONUS_PUT = NEW_USER_BONUS_PUT;

var NEWER_PUT = "user/extState/isNewer/PUT";

exports.NEWER_PUT = NEWER_PUT;

var NOVICE_PUT = "user/extState/isNovice/PUT";

exports.NOVICE_PUT = NOVICE_PUT;

var SUBSCRIBE_SCHEDULE_PUT = "user/extState/isSubscribeSchedule/PUT";

exports.SUBSCRIBE_SCHEDULE_PUT = SUBSCRIBE_SCHEDULE_PUT;

var BIND_PHONE_NUMBER_PUT = "user/extState/isBindPhoneNumber/PUT";

exports.BIND_PHONE_NUMBER_PUT = BIND_PHONE_NUMBER_PUT;

var AFTER_SHARE_PROMPT_PUT = "user/extState/isCloseAfterSharePrompt/PUT";

exports.AFTER_SHARE_PROMPT_PUT = AFTER_SHARE_PROMPT_PUT;

var EXPIRE_TICKET_NUMBER_PUT = "user/extState/expireTicketNumber/PUT";

exports.EXPIRE_TICKET_NUMBER_PUT = EXPIRE_TICKET_NUMBER_PUT;

var NEW_TICKET_NUMBER_PUT = "user/extState/newTicketNumber/PUT";

exports.NEW_TICKET_NUMBER_PUT = NEW_TICKET_NUMBER_PUT;

var ALL_TICKET_VALUE_PUT = "user/extState/allTicketValue/PUT";

exports.ALL_TICKET_VALUE_PUT = ALL_TICKET_VALUE_PUT;

var NEW_BADGE_NUMBER_PUT = "user/extState/newBadgeNumber/PUT";

exports.NEW_BADGE_NUMBER_PUT = NEW_BADGE_NUMBER_PUT;

var MY_INVITE_INFO_NUMBER_PUT = "user/extState/myInviteInfoNumber/PUT";

exports.MY_INVITE_INFO_NUMBER_PUT = MY_INVITE_INFO_NUMBER_PUT;

var PERSONAL_EXPIRE_NUMBER_PUT = "user/extState/personalExpireNumber/PUT";

exports.PERSONAL_EXPIRE_NUMBER_PUT = PERSONAL_EXPIRE_NUMBER_PUT;

var NEWER_GUIDE_USER_PUT = "user/extState/isNewerGuideUser/PUT";

exports.NEWER_GUIDE_USER_PUT = NEWER_GUIDE_USER_PUT;

var HAS_SHOWED_TOOLTIP_PUT = "user/extState/hasShowedTooltip/PUT";

exports.HAS_SHOWED_TOOLTIP_PUT = HAS_SHOWED_TOOLTIP_PUT;

var RECHARGE_AB_CATEGORY_PUT = "user/extState/rechargeABCategory/PUT";

exports.RECHARGE_AB_CATEGORY_PUT = RECHARGE_AB_CATEGORY_PUT;

var MESSAGE_SUBSCRIBE_LIST_PUT = "user/messageSubscribe/messageSubscribeList/PUT";

exports.MESSAGE_SUBSCRIBE_LIST_PUT = MESSAGE_SUBSCRIBE_LIST_PUT;

var USER_SUBSCRIBE_MAP_PUT = "user/messageSubscribe/userSubscribeMapPut/PUT";

exports.USER_SUBSCRIBE_MAP_PUT = USER_SUBSCRIBE_MAP_PUT;

var ORDER_MESSAGES_PUT = "user/messageSubscribe/orderMessages/PUT";

exports.ORDER_MESSAGES_PUT = ORDER_MESSAGES_PUT;

var MESSAGE_MAP_COUNT_PUT = "user/messageMapCount/PUT";

exports.MESSAGE_MAP_COUNT_PUT = MESSAGE_MAP_COUNT_PUT;

var CLASS_MAP_PUT = "class/full/PUT";

exports.CLASS_MAP_PUT = CLASS_MAP_PUT;

var CLASS_SMALL_MAP_PUT = "class/small/PUT";

exports.CLASS_SMALL_MAP_PUT = CLASS_SMALL_MAP_PUT;

var SCHEDULE_MAP_PUT = "schedule/full/PUT";

exports.SCHEDULE_MAP_PUT = SCHEDULE_MAP_PUT;

var SCHEDULE_SMALL_MAP_PUT = "schedule/small/PUT";

exports.SCHEDULE_SMALL_MAP_PUT = SCHEDULE_SMALL_MAP_PUT;

var CAMP_MAP_PUT = "camp/full/PUT";

exports.CAMP_MAP_PUT = CAMP_MAP_PUT;

var PERSONAL_CAMP_MAP_PUT = "personal/camp/full/PUT";

exports.PERSONAL_CAMP_MAP_PUT = PERSONAL_CAMP_MAP_PUT;

var PERSONAL_SCHEDULE_MAP_PUT = "personal/schedule/full/PUT";

exports.PERSONAL_SCHEDULE_MAP_PUT = PERSONAL_SCHEDULE_MAP_PUT;

var PERSONAL_MAP_PUT = "personal/full/PUT";

exports.PERSONAL_MAP_PUT = PERSONAL_MAP_PUT;

var BOX_MAP_PUT = "box/full/PUT";

exports.BOX_MAP_PUT = BOX_MAP_PUT;

var BOX_SMALL_MAP_PUT = "box/small/PUT";

exports.BOX_SMALL_MAP_PUT = BOX_SMALL_MAP_PUT;

var TRAINER_MAP_PUT = "trainer/full/PUT";

exports.TRAINER_MAP_PUT = TRAINER_MAP_PUT;

var TRAINER_SMALL_MAP_PUT = "trainer/small/PUT";

exports.TRAINER_SMALL_MAP_PUT = TRAINER_SMALL_MAP_PUT;

var ONLINE_CAMP_TRAINER_LIST_PUT = "trainer/list/PUT";

exports.ONLINE_CAMP_TRAINER_LIST_PUT = ONLINE_CAMP_TRAINER_LIST_PUT;

var POSITION_MAP_PUT = "position/PUT";

exports.POSITION_MAP_PUT = POSITION_MAP_PUT;

var POSITION_RULES_MAP_PUT = "position/rules/PUT";

exports.POSITION_RULES_MAP_PUT = POSITION_RULES_MAP_PUT;

var PROMOTION_MAP_PUT = "promotion/PUT";

exports.PROMOTION_MAP_PUT = PROMOTION_MAP_PUT;

var PROMOTION_POSITION_RELATE_MAP_PUT = "promotion/position/relate/PUT";

exports.PROMOTION_POSITION_RELATE_MAP_PUT = PROMOTION_POSITION_RELATE_MAP_PUT;

var POSITION_RELATE_MAP_PUT = "position/relate/map/PUT";

exports.POSITION_RELATE_MAP_PUT = POSITION_RELATE_MAP_PUT;

var POSITION_SORTED_RELATE_MAP_PUT = "position/sorted/relate/map/PUT";

exports.POSITION_SORTED_RELATE_MAP_PUT = POSITION_SORTED_RELATE_MAP_PUT;

var VIP_LEVEL_CONFIG_MAP_PUT = "vip/level/config/PUT";

exports.VIP_LEVEL_CONFIG_MAP_PUT = VIP_LEVEL_CONFIG_MAP_PUT;

var VIP_EQUITY_MAP_PUT = "vip/equity/map/PUT";

exports.VIP_EQUITY_MAP_PUT = VIP_EQUITY_MAP_PUT;

var VIP_TASK_MAP_PUT = "vip/task/map/PUT";

exports.VIP_TASK_MAP_PUT = VIP_TASK_MAP_PUT;

var BOX_EXTRA_MAP_PUT = "box/extra/PUT";

exports.BOX_EXTRA_MAP_PUT = BOX_EXTRA_MAP_PUT;

var DATE_BOX_SCHEDULES_MAP_PUT = "class/dateBoxSchedules/PUT";

exports.DATE_BOX_SCHEDULES_MAP_PUT = DATE_BOX_SCHEDULES_MAP_PUT;

var CLASS_PRICE_MAP_PUT = "class/price/map/PUT";

exports.CLASS_PRICE_MAP_PUT = CLASS_PRICE_MAP_PUT;

var BOX_LIST_PUT = "box/list/PUT";

exports.BOX_LIST_PUT = BOX_LIST_PUT;

var BOX_NAME_PUT = "box/name/PUT";

exports.BOX_NAME_PUT = BOX_NAME_PUT;

var BOX_BOOKING_CONFIRM_INFO_PUT = "box/booking/confirm/info/PUT";

exports.BOX_BOOKING_CONFIRM_INFO_PUT = BOX_BOOKING_CONFIRM_INFO_PUT;

var BOX_BOOKING_DETAIL_PUT = "box/booking/detail/PUT";

exports.BOX_BOOKING_DETAIL_PUT = BOX_BOOKING_DETAIL_PUT;

var CLASS_CONTENT_CITY_PUT = "class/list/course/city/PUT";

exports.CLASS_CONTENT_CITY_PUT = CLASS_CONTENT_CITY_PUT;

var CLASS_CONTENT_DATES_PUT = "class/list/course/dates/PUT";

exports.CLASS_CONTENT_DATES_PUT = CLASS_CONTENT_DATES_PUT;

var CLASS_SCHEDULES_TIME_PUT = "class/list/course/time/PUT";

exports.CLASS_SCHEDULES_TIME_PUT = CLASS_SCHEDULES_TIME_PUT;

var CLASS_BOX_FILTER_PUT = "class/list/course/boxFilter/PUT";

exports.CLASS_BOX_FILTER_PUT = CLASS_BOX_FILTER_PUT;

var CLASS_CATEGORY_FILTER_PUT = "class/list/course/categoryFilter/PUT";

exports.CLASS_CATEGORY_FILTER_PUT = CLASS_CATEGORY_FILTER_PUT;

var CLASS_SCHEDULES_SUBSCRIBE_PUT = "class/list/subscribe/PUT";

exports.CLASS_SCHEDULES_SUBSCRIBE_PUT = CLASS_SCHEDULES_SUBSCRIBE_PUT;

var CLASS_BOX_TIME_PUT = "class/list/box/time/PUT";

exports.CLASS_BOX_TIME_PUT = CLASS_BOX_TIME_PUT;

var CLASS_BOX_DATES_PUT = "class/list/box/dates/PUT";

exports.CLASS_BOX_DATES_PUT = CLASS_BOX_DATES_PUT;

var CLASS_BOX_ID_PUT = "class/list/box/id/PUT";

exports.CLASS_BOX_ID_PUT = CLASS_BOX_ID_PUT;

var CLASS_LIST_TRAINER_TIME_PUT = "class/list/trainer/time/PUT";

exports.CLASS_LIST_TRAINER_TIME_PUT = CLASS_LIST_TRAINER_TIME_PUT;

var CLASS_LIST_TRAINER_DATES_PUT = "class/list/trainer/dates/PUT";

exports.CLASS_LIST_TRAINER_DATES_PUT = CLASS_LIST_TRAINER_DATES_PUT;

var CLASS_LIST_TRAINER_BOXIDS_PUT = "class/list/trainer/boxIds/PUT";

exports.CLASS_LIST_TRAINER_BOXIDS_PUT = CLASS_LIST_TRAINER_BOXIDS_PUT;

var CLASS_DETAIL_PUT = "class/detail/PUT";

exports.CLASS_DETAIL_PUT = CLASS_DETAIL_PUT;

var CLASS_BOOKING_CONFIRM_PUT = "class/booking/confirm/PUT";

exports.CLASS_BOOKING_CONFIRM_PUT = CLASS_BOOKING_CONFIRM_PUT;

var CLASS_BOOKING_SUCCESS_PUT = "class/booking/success/PUT";

exports.CLASS_BOOKING_SUCCESS_PUT = CLASS_BOOKING_SUCCESS_PUT;

var CLASS_BOOKING_DETAIL_PUT = "class/booking/detail/PUT";

exports.CLASS_BOOKING_DETAIL_PUT = CLASS_BOOKING_DETAIL_PUT;

var PERSONAL_LIST_PUT = "personal/list/PUT";

exports.PERSONAL_LIST_PUT = PERSONAL_LIST_PUT;

var PERSONAL_BOX_LIST_PUT = "personal/box/list/PUT";

exports.PERSONAL_BOX_LIST_PUT = PERSONAL_BOX_LIST_PUT;

var PERSONAL_CLASS_DETAIL_PUT = "personal/class/detail/PUT";

exports.PERSONAL_CLASS_DETAIL_PUT = PERSONAL_CLASS_DETAIL_PUT;

var PERSONAL_BOOKING_INFO_PUT = "personal/booking/info/PUT";

exports.PERSONAL_BOOKING_INFO_PUT = PERSONAL_BOOKING_INFO_PUT;

var PERSONAL_BOOKING_DETAIL_PUT = "personal/booking/detail/PUT";

exports.PERSONAL_BOOKING_DETAIL_PUT = PERSONAL_BOOKING_DETAIL_PUT;

var PERSONAL_BOOKING_SUCCESS_INFO_PUT = "personal/booking/success/info/PUT";

exports.PERSONAL_BOOKING_SUCCESS_INFO_PUT = PERSONAL_BOOKING_SUCCESS_INFO_PUT;

var OLD_PERSONAL_BOOKING_DETAIL_PUT = "old/personal/booking/detail/PUT";

exports.OLD_PERSONAL_BOOKING_DETAIL_PUT = OLD_PERSONAL_BOOKING_DETAIL_PUT;

var TRAINER_PERSONAL_LIST_PUT = "personal/list/trainer/PUT";

exports.TRAINER_PERSONAL_LIST_PUT = TRAINER_PERSONAL_LIST_PUT;

var TRAIN_BOOKING_DATE_PUT = "train/booking/date/PUT";

exports.TRAIN_BOOKING_DATE_PUT = TRAIN_BOOKING_DATE_PUT;

var PERSONAL_TRAIN_LIST_PUT = "personal/train/list/PUT";

exports.PERSONAL_TRAIN_LIST_PUT = PERSONAL_TRAIN_LIST_PUT;

var PERSONAL_CANCELED_TRAIN_LIST_PUT = "personal/canceled/train/list/PUT";

exports.PERSONAL_CANCELED_TRAIN_LIST_PUT = PERSONAL_CANCELED_TRAIN_LIST_PUT;

var CAMPS_LIST_PUT = "camp/list/PUT";

exports.CAMPS_LIST_PUT = CAMPS_LIST_PUT;

var CAMP_LIST_CITY_PUT = "camp/list/city/PUT";

exports.CAMP_LIST_CITY_PUT = CAMP_LIST_CITY_PUT;

var CAMP_DETAIL_PUT = "camp/detail/PUT";

exports.CAMP_DETAIL_PUT = CAMP_DETAIL_PUT;

var CAMP_SUBSCRIBE_PUT = "camp/subscribe/PUT";

exports.CAMP_SUBSCRIBE_PUT = CAMP_SUBSCRIBE_PUT;

var OFFLINE_CAMP_SCHEDULE_SHOW_APPLICABLE = "offline/camp/schedule/show/applicable/PUT";

exports.OFFLINE_CAMP_SCHEDULE_SHOW_APPLICABLE = OFFLINE_CAMP_SCHEDULE_SHOW_APPLICABLE;

var CAMP_BOOKING_CONFIRM_INFO_PUT = "camp/booking/confirm/info/PUT";

exports.CAMP_BOOKING_CONFIRM_INFO_PUT = CAMP_BOOKING_CONFIRM_INFO_PUT;

var CITY_NEW_CAMP_SHOW_STATUS_ON_NAV_BAR_PUT = "city/new/camp/show/status/on/nav/bar/PUT";

exports.CITY_NEW_CAMP_SHOW_STATUS_ON_NAV_BAR_PUT = CITY_NEW_CAMP_SHOW_STATUS_ON_NAV_BAR_PUT;

var NEW_CAMP_STATUS_ON_CAMP_PUT = "new/camp/status/on/camp/PUT";

exports.NEW_CAMP_STATUS_ON_CAMP_PUT = NEW_CAMP_STATUS_ON_CAMP_PUT;

var CAMP_BOOKING_DETAIL_PUT = "camp/booking/detail/PUT";

exports.CAMP_BOOKING_DETAIL_PUT = CAMP_BOOKING_DETAIL_PUT;

var BOX_CAMPS_LIST_PUT = "box/camps/list/PUT";

exports.BOX_CAMPS_LIST_PUT = BOX_CAMPS_LIST_PUT;

var CAMPS_SMALL_PUT = "camps/small/PUT";

exports.CAMPS_SMALL_PUT = CAMPS_SMALL_PUT;

var BOX_CAMPS_PUT = "box/camps/PUT";

exports.BOX_CAMPS_PUT = BOX_CAMPS_PUT;

var TRAINER_SCHEDULE_IDS_PUT = "camp/list/trainer/PUT";

exports.TRAINER_SCHEDULE_IDS_PUT = TRAINER_SCHEDULE_IDS_PUT;

var MY_GIVEN_LIST_PUT = "my/given/list/PUT";

exports.MY_GIVEN_LIST_PUT = MY_GIVEN_LIST_PUT;

var GIVE_CONFIRM_BOOKING_CONFIRM_INFO_PUT = "give/confirm/booking/confirm/info/PUT";

exports.GIVE_CONFIRM_BOOKING_CONFIRM_INFO_PUT = GIVE_CONFIRM_BOOKING_CONFIRM_INFO_PUT;

var GIVE_CLASS_RECEIVE_PUT = "give/class/receive/PUT";

exports.GIVE_CLASS_RECEIVE_PUT = GIVE_CLASS_RECEIVE_PUT;

var GIVE_CLASS_BOOKING_DETAIL_PUT = "give/class/booking/detail/PUT";

exports.GIVE_CLASS_BOOKING_DETAIL_PUT = GIVE_CLASS_BOOKING_DETAIL_PUT;

var GIVE_CLASS_DETAIL_PUT = "give/class/detail/PUT";

exports.GIVE_CLASS_DETAIL_PUT = GIVE_CLASS_DETAIL_PUT;

var GIVE_CLASS_BALANCE_PAY_PUT = "give/class/balance/pay/PUT";

exports.GIVE_CLASS_BALANCE_PAY_PUT = GIVE_CLASS_BALANCE_PAY_PUT;

var TRAINER_PROFILE_PUT = "trainer/profile/PUT";

exports.TRAINER_PROFILE_PUT = TRAINER_PROFILE_PUT;

var MY_BOOKING_INFO_PUT = "my/booking/info/PUT";

exports.MY_BOOKING_INFO_PUT = MY_BOOKING_INFO_PUT;

var BOOKING_RECORDS_PUT = "booking/records/PUT";

exports.BOOKING_RECORDS_PUT = BOOKING_RECORDS_PUT;

var RECHARGE_CONFIRM_PUT = "recharge/confirm/PUT";

exports.RECHARGE_CONFIRM_PUT = RECHARGE_CONFIRM_PUT;

var MY_INFO_PUT = "my/info/PUT";

exports.MY_INFO_PUT = MY_INFO_PUT;

var USER_EXT_PUT = "user/ext/put";

exports.USER_EXT_PUT = USER_EXT_PUT;

var VIP_DETAIL_INFO_PUT = "VIP_DETAIL_INFO_PUT";

exports.VIP_DETAIL_INFO_PUT = VIP_DETAIL_INFO_PUT;

var SUPER_CHANGE_RECORDS_PUT = "SUPER_CHANGE_RECORDS_PUT";

exports.SUPER_CHANGE_RECORDS_PUT = SUPER_CHANGE_RECORDS_PUT;

var SUPER_RANK_MAP_PUT = "super/rank/map/PUT";

exports.SUPER_RANK_MAP_PUT = SUPER_RANK_MAP_PUT;

var GROUP_RANK_MAP_PUT = "group/rank/map/PUT";

exports.GROUP_RANK_MAP_PUT = GROUP_RANK_MAP_PUT;

var MY_TICKETS_PUT = "my/tickets/PUT";

exports.MY_TICKETS_PUT = MY_TICKETS_PUT;

var INVALID_TICKETS_PUT = "invalid/tickets/PUT";

exports.INVALID_TICKETS_PUT = INVALID_TICKETS_PUT;

var ONLINE_CAMP_HOME_DATA_PUT = "online/camp/list/PUT";

exports.ONLINE_CAMP_HOME_DATA_PUT = ONLINE_CAMP_HOME_DATA_PUT;

var ONLINE_CAMP_SCHEDULE_MAP_PUT = "online/camp/schedule/map/PUT";

exports.ONLINE_CAMP_SCHEDULE_MAP_PUT = ONLINE_CAMP_SCHEDULE_MAP_PUT;

var ONLINE_COURSE_LIST_PUT = "online/course/list//PUT";

exports.ONLINE_COURSE_LIST_PUT = ONLINE_COURSE_LIST_PUT;

var ONLINE_CAMP_LIST_PUT = "online/camp/list/PUT";

exports.ONLINE_CAMP_LIST_PUT = ONLINE_CAMP_LIST_PUT;

var ONLINE_CAMP_DETAIL_PUT = "online/camp/detail/PUT";

exports.ONLINE_CAMP_DETAIL_PUT = ONLINE_CAMP_DETAIL_PUT;

var ONLINE_CAMP_DETAIL_SCHEDULE_PUT = "online/camp/detail/schedule/PUT";

exports.ONLINE_CAMP_DETAIL_SCHEDULE_PUT = ONLINE_CAMP_DETAIL_SCHEDULE_PUT;

var ONLINE_CAMP_SCHEDULE_SHOW_APPLICABLE = "online/camp/schedule/show/applicable/PUT";

exports.ONLINE_CAMP_SCHEDULE_SHOW_APPLICABLE = ONLINE_CAMP_SCHEDULE_SHOW_APPLICABLE;

var ONLINE_CAMP_SCHEDULE_SELECTED_CITY = "online/camp/schedule/selected/city/PUT";

exports.ONLINE_CAMP_SCHEDULE_SELECTED_CITY = ONLINE_CAMP_SCHEDULE_SELECTED_CITY;

var ONLINE_CAMP_SCHEDULE_SELECTED_SCHEDULE = "online/camp/schedule/selected/schedule/PUT";

exports.ONLINE_CAMP_SCHEDULE_SELECTED_SCHEDULE = ONLINE_CAMP_SCHEDULE_SELECTED_SCHEDULE;

var ONLINE_CAMP_FIRST_SHOW_SELECT_SCHEDULE_MODAL_STATE = "online/camp/first/show/select/schedule/modal/state/PUT";

exports.ONLINE_CAMP_FIRST_SHOW_SELECT_SCHEDULE_MODAL_STATE = ONLINE_CAMP_FIRST_SHOW_SELECT_SCHEDULE_MODAL_STATE;

var APP_CLASS_TYPE_PUT = "app/class/type/PUT";

exports.APP_CLASS_TYPE_PUT = APP_CLASS_TYPE_PUT;

var BADGE_INFO_PUT = "badge/info/PUT";

exports.BADGE_INFO_PUT = BADGE_INFO_PUT;

var BADGE_DETAIL_PUT = "badge/detail/PUT";

exports.BADGE_DETAIL_PUT = BADGE_DETAIL_PUT;

var BADGE_USER_LIST_PUT = "badge/user/list/PUT";

exports.BADGE_USER_LIST_PUT = BADGE_USER_LIST_PUT;

var PICTURE_SHARE_URL_PUT = "picture/share/url/PUT";

exports.PICTURE_SHARE_URL_PUT = PICTURE_SHARE_URL_PUT;

var SUPERALLIANCETICKET_IDENTITY_PUT = "superAllianceTicket/identity/PUT";

exports.SUPERALLIANCETICKET_IDENTITY_PUT = SUPERALLIANCETICKET_IDENTITY_PUT;

var WXPAY_ORDER_LIST_PUT = "WXPAY_ORDER_LIST_PUT";

exports.WXPAY_ORDER_LIST_PUT = WXPAY_ORDER_LIST_PUT;

var WXPAY_ORDER_LIST_INVOICE_PUT = "WXPAY_ORDER_LIST_INVOICE_PUT";

exports.WXPAY_ORDER_LIST_INVOICE_PUT = WXPAY_ORDER_LIST_INVOICE_PUT;

var INVOICE_ORDER_TYPE_PUT = "INVOICE_ORDER_TYPE_PUT";

exports.INVOICE_ORDER_TYPE_PUT = INVOICE_ORDER_TYPE_PUT;

var WXPAY_INVOICE_HISTORY_PUT = "WXPAY_INVOICE_HISTORY_PUT";

exports.WXPAY_INVOICE_HISTORY_PUT = WXPAY_INVOICE_HISTORY_PUT;

var BALANCE_RECORDS_PUT = "BALANCE_RECORDS_PUT";

exports.BALANCE_RECORDS_PUT = BALANCE_RECORDS_PUT;

var BALANCE_INFO_PUT = "BALANCE_INFO_PUT";

exports.BALANCE_INFO_PUT = BALANCE_INFO_PUT;

var BALANCE_CLEAR_PUT = "BALANCE_CLEAR_PUT";

exports.BALANCE_CLEAR_PUT = BALANCE_CLEAR_PUT;

var REASON_LIST_PUT = "REASON_LIST_PUT";

exports.REASON_LIST_PUT = REASON_LIST_PUT;

var SCORE_LIST_PUT = "SCORE_LIST_PUT";

exports.SCORE_LIST_PUT = SCORE_LIST_PUT;

var NOVICE_CLASS_MAP_PUT = "novice/class/map/PUT";

exports.NOVICE_CLASS_MAP_PUT = NOVICE_CLASS_MAP_PUT;

var NOVICE_CLASS_LIST_PUT = "novice/class/list/PUT";

exports.NOVICE_CLASS_LIST_PUT = NOVICE_CLASS_LIST_PUT;