var BOX_BANNER = "boxBanner", BOX_ADS = "boxAds", CLASS_BEFORE_OPEN = "classBeforeOpen", CLASS_ADS = "classAds", COURSE_BOOKING_SUCCESS = "courseBookingSuccess", SUPERMONKEY_CARD_MENU_ROW = "supermonkeyCardMenuRow";

module.exports = {
    BOX_BANNER: BOX_BANNER,
    BOX_ADS: BOX_ADS,
    CLASS_BEFORE_OPEN: CLASS_BEFORE_OPEN,
    CLASS_ADS: CLASS_ADS,
    COURSE_BOOKING_SUCCESS: COURSE_BOOKING_SUCCESS,
    SUPERMONKEY_CARD_MENU_ROW: SUPERMONKEY_CARD_MENU_ROW
};